// use remill_semantics_parser::remill_semantics;
use crate::iform_semantics::PUNPCKLDQV::PUNPCKLDQVSemanticsVisitor;
use xed_enum::*;

use crate::x86_machine::X86MachineState;

pub mod iform_aaa;
pub mod iform_adc;

impl X86MachineState<'_> {
    fn apply_instruction(&mut self, instr: X86Instruction) {
        match instr {
            X86Instruction::AAA(aaa) => self.apply_iform_aaa(aaa),
            X86Instruction::ADC(adc) => self.apply_iform_adc(adc),
            _ => todo!(),
        }
    }
}

// remill_semantics!();

pub mod PUNPCKLDQV;

pub struct SemanticsVisitor {}
impl X86InstructionVisitor for SemanticsVisitor {
    fn visit_PUNPCKLDQ(&self, _0: PUNPCKLDQ) {
        PUNPCKLDQVSemanticsVisitor {}.visit(_0)
    }
    fn visit_CVTPS2PI(&self, _0: CVTPS2PI) {}
    fn visit_VPSRLW(&self, _0: VPSRLW) {}
    fn visit_VPUNPCKLBW(&self, _0: VPUNPCKLBW) {}
    fn visit_VMOVMSKPD(&self, _0: VMOVMSKPD) {}
    fn visit_IRETD(&self, _0: IRETD) {}
    fn visit_VFNMSUBPS(&self, _0: VFNMSUBPS) {}
    fn visit_FDIVRP(&self, _0: FDIVRP) {}
    fn visit_INSERTPS(&self, _0: INSERTPS) {}
    fn visit_VHADDPS(&self, _0: VHADDPS) {}
    fn visit_VFMSUBADD132PS(&self, _0: VFMSUBADD132PS) {}
    fn visit_VMOVDQA32(&self, _0: VMOVDQA32) {}
    fn visit_CLFLUSH(&self, _0: CLFLUSH) {}
    fn visit_VPMOVQD(&self, _0: VPMOVQD) {}
    fn visit_VPSCATTERDD(&self, _0: VPSCATTERDD) {}
    fn visit_VCVTTPS2QQ(&self, _0: VCVTTPS2QQ) {}
    fn visit_PINSRQ(&self, _0: PINSRQ) {}
    fn visit_VPMOVUSQW(&self, _0: VPMOVUSQW) {}
    fn visit_BLCIC(&self, _0: BLCIC) {}
    fn visit_AESDEC128KL(&self, _0: AESDEC128KL) {}
    fn visit_VFMSUBSD(&self, _0: VFMSUBSD) {}
    fn visit_PUSH(&self, _0: PUSH) {}
    fn visit_VFMSUBADD231PS(&self, _0: VFMSUBADD231PS) {}
    fn visit_PREFETCHT2(&self, _0: PREFETCHT2) {}
    fn visit_VSCATTERDPS(&self, _0: VSCATTERDPS) {}
    fn visit_UIRET(&self, _0: UIRET) {}
    fn visit_VPSUBW(&self, _0: VPSUBW) {}
    fn visit_WRFSBASE(&self, _0: WRFSBASE) {}
    fn visit_VMULSS(&self, _0: VMULSS) {}
    fn visit_VPSRAVQ(&self, _0: VPSRAVQ) {}
    fn visit_VPMOVWB(&self, _0: VPMOVWB) {}
    fn visit_VRANGESD(&self, _0: VRANGESD) {}
    fn visit_SAHF(&self, _0: SAHF) {}
    fn visit_CVTTPD2DQ(&self, _0: CVTTPD2DQ) {}
    fn visit_VFPCLASSPS(&self, _0: VFPCLASSPS) {}
    fn visit_VPCMOV(&self, _0: VPCMOV) {}
    fn visit_VBROADCASTSD(&self, _0: VBROADCASTSD) {}
    fn visit_ADDSUBPD(&self, _0: ADDSUBPD) {}
    fn visit_PFCMPEQ(&self, _0: PFCMPEQ) {}
    fn visit_BNDSTX(&self, _0: BNDSTX) {}
    fn visit_MOVZX(&self, _0: MOVZX) {}
    fn visit_VCVTSS2SI(&self, _0: VCVTSS2SI) {}
    fn visit_CVTTPS2PI(&self, _0: CVTTPS2PI) {}
    fn visit_VFIXUPIMMSD(&self, _0: VFIXUPIMMSD) {}
    fn visit_VPGATHERDQ(&self, _0: VPGATHERDQ) {}
    fn visit_SETNP(&self, _0: SETNP) {}
    fn visit_PSRLQ(&self, _0: PSRLQ) {}
    fn visit_MOVDIR64B(&self, _0: MOVDIR64B) {}
    fn visit_RSQRTSS(&self, _0: RSQRTSS) {}
    fn visit_SERIALIZE(&self, _0: SERIALIZE) {}
    fn visit_VCVTDQ2PS(&self, _0: VCVTDQ2PS) {}
    fn visit_VFNMSUB231SS(&self, _0: VFNMSUB231SS) {}
    fn visit_VFIXUPIMMSS(&self, _0: VFIXUPIMMSS) {}
    fn visit_VBROADCASTI64X2(&self, _0: VBROADCASTI64X2) {}
    fn visit_VPBLENDMW(&self, _0: VPBLENDMW) {}
    fn visit_LAHF(&self, _0: LAHF) {}
    fn visit_VCVTPD2DQ(&self, _0: VCVTPD2DQ) {}
    fn visit_WRGSBASE(&self, _0: WRGSBASE) {}
    fn visit_VCVTPS2DQ(&self, _0: VCVTPS2DQ) {}
    fn visit_RDFSBASE(&self, _0: RDFSBASE) {}
    fn visit_VCOMISD(&self, _0: VCOMISD) {}
    fn visit_MOVAPS(&self, _0: MOVAPS) {}
    fn visit_VCVTUQQ2PD(&self, _0: VCVTUQQ2PD) {}
    fn visit_VPSRAW(&self, _0: VPSRAW) {}
    fn visit_VFMSUBADD213PD(&self, _0: VFMSUBADD213PD) {}
    fn visit_CVTPI2PS(&self, _0: CVTPI2PS) {}
    fn visit_KXNORQ(&self, _0: KXNORQ) {}
    fn visit_VPCONFLICTD(&self, _0: VPCONFLICTD) {}
    fn visit_JL(&self, _0: JL) {}
    fn visit_COMISD(&self, _0: COMISD) {}
    fn visit_FSQRT(&self, _0: FSQRT) {}
    fn visit_CVTPD2PI(&self, _0: CVTPD2PI) {}
    fn visit_VPACKUSDW(&self, _0: VPACKUSDW) {}
    fn visit_VFMADDSUB132PS(&self, _0: VFMADDSUB132PS) {}
    fn visit_VFNMSUB213SD(&self, _0: VFNMSUB213SD) {}
    fn visit_VPOPCNTB(&self, _0: VPOPCNTB) {}
    fn visit_PHSUBW(&self, _0: PHSUBW) {}
    fn visit_EXTRACTPS(&self, _0: EXTRACTPS) {}
    fn visit_VCVTSD2SS(&self, _0: VCVTSD2SS) {}
    fn visit_VLDDQU(&self, _0: VLDDQU) {}
    fn visit_OUT(&self, _0: OUT) {}
    fn visit_T1MSKC(&self, _0: T1MSKC) {}
    fn visit_ADC(&self, _0: ADC) {}
    fn visit_PAUSE(&self, _0: PAUSE) {}
    fn visit_VBLENDMPD(&self, _0: VBLENDMPD) {}
    fn visit_CMC(&self, _0: CMC) {}
    fn visit_VBROADCASTSS(&self, _0: VBROADCASTSS) {}
    fn visit_VMAXSS(&self, _0: VMAXSS) {}
    fn visit_LSS(&self, _0: LSS) {}
    fn visit_PMOVZXBD(&self, _0: PMOVZXBD) {}
    fn visit_GF2P8AFFINEINVQB(&self, _0: GF2P8AFFINEINVQB) {}
    fn visit_VMOVLPD(&self, _0: VMOVLPD) {}
    fn visit_STAC(&self, _0: STAC) {}
    fn visit_ADDSD(&self, _0: ADDSD) {}
    fn visit_MCOMMIT(&self, _0: MCOMMIT) {}
    fn visit_WRMSR(&self, _0: WRMSR) {}
    fn visit_VCVTTSS2SI(&self, _0: VCVTTSS2SI) {}
    fn visit_VMOVNTDQ(&self, _0: VMOVNTDQ) {}
    fn visit_PFCMPGE(&self, _0: PFCMPGE) {}
    fn visit_VPSRLVD(&self, _0: VPSRLVD) {}
    fn visit_VBLENDVPS(&self, _0: VBLENDVPS) {}
    fn visit_PHSUBD(&self, _0: PHSUBD) {}
    fn visit_VCOMPRESSPS(&self, _0: VCOMPRESSPS) {}
    fn visit_VGETMANTSS(&self, _0: VGETMANTSS) {}
    fn visit_VERR(&self, _0: VERR) {}
    fn visit_SETZ(&self, _0: SETZ) {}
    fn visit_PCLMULQDQ(&self, _0: PCLMULQDQ) {}
    fn visit_VPHADDUBQ(&self, _0: VPHADDUBQ) {}
    fn visit_VPMULHUW(&self, _0: VPMULHUW) {}
    fn visit_VPEXPANDQ(&self, _0: VPEXPANDQ) {}
    fn visit_FISTP(&self, _0: FISTP) {}
    fn visit_KANDNW(&self, _0: KANDNW) {}
    fn visit_PACKUSWB(&self, _0: PACKUSWB) {}
    fn visit_BNDCN(&self, _0: BNDCN) {}
    fn visit_RCR(&self, _0: RCR) {}
    fn visit_CWDE(&self, _0: CWDE) {}
    fn visit_XSAVEC(&self, _0: XSAVEC) {}
    fn visit_VMAXSD(&self, _0: VMAXSD) {}
    fn visit_VHSUBPD(&self, _0: VHSUBPD) {}
    fn visit_HSUBPD(&self, _0: HSUBPD) {}
    fn visit_ENCLV(&self, _0: ENCLV) {}
    fn visit_HSUBPS(&self, _0: HSUBPS) {}
    fn visit_VPERMPD(&self, _0: VPERMPD) {}
    fn visit_VRCP14PD(&self, _0: VRCP14PD) {}
    fn visit_VMOVDQU8(&self, _0: VMOVDQU8) {}
    fn visit_XRESLDTRK(&self, _0: XRESLDTRK) {}
    fn visit_VSQRTPD(&self, _0: VSQRTPD) {}
    fn visit_VMSAVE(&self, _0: VMSAVE) {}
    fn visit_FLDPI(&self, _0: FLDPI) {}
    fn visit_VMOVSD(&self, _0: VMOVSD) {}
    fn visit_PMINSW(&self, _0: PMINSW) {}
    fn visit_VMINSS(&self, _0: VMINSS) {}
    fn visit_SQRTSD(&self, _0: SQRTSD) {}
    fn visit_CMOVP(&self, _0: CMOVP) {}
    fn visit_SAVEPREVSSP(&self, _0: SAVEPREVSSP) {}
    fn visit_SETNZ(&self, _0: SETNZ) {}
    fn visit_VPSUBSB(&self, _0: VPSUBSB) {}
    fn visit_VPERMT2PD(&self, _0: VPERMT2PD) {}
    fn visit_VPERMT2PS(&self, _0: VPERMT2PS) {}
    fn visit_NOP(&self, _0: NOP) {}
    fn visit_VPSHLB(&self, _0: VPSHLB) {}
    fn visit_VPMOVUSDW(&self, _0: VPMOVUSDW) {}
    fn visit_CMOVO(&self, _0: CMOVO) {}
    fn visit_RSM(&self, _0: RSM) {}
    fn visit_PFPNACC(&self, _0: PFPNACC) {}
    fn visit_VSHUFI64X2(&self, _0: VSHUFI64X2) {}
    fn visit_INSB(&self, _0: INSB) {}
    fn visit_VBROADCASTI128(&self, _0: VBROADCASTI128) {}
    fn visit_CQO(&self, _0: CQO) {}
    fn visit_VPMASKMOVD(&self, _0: VPMASKMOVD) {}
    fn visit_STOSQ(&self, _0: STOSQ) {}
    fn visit_VPMACSSDD(&self, _0: VPMACSSDD) {}
    fn visit_FUCOMPP(&self, _0: FUCOMPP) {}
    fn visit_MWAITX(&self, _0: MWAITX) {}
    fn visit_VPSRLD(&self, _0: VPSRLD) {}
    fn visit_VPMINSD(&self, _0: VPMINSD) {}
    fn visit_VBLENDPD(&self, _0: VBLENDPD) {}
    fn visit_VPSLLDQ(&self, _0: VPSLLDQ) {}
    fn visit_CDQ(&self, _0: CDQ) {}
    fn visit_VFNMSUB132SD(&self, _0: VFNMSUB132SD) {}
    fn visit_SUB(&self, _0: SUB) {}
    fn visit_VPROLD(&self, _0: VPROLD) {}
    fn visit_ROUNDPS(&self, _0: ROUNDPS) {}
    fn visit_BNDCU(&self, _0: BNDCU) {}
    fn visit_KANDND(&self, _0: KANDND) {}
    fn visit_ROUNDSD(&self, _0: ROUNDSD) {}
    fn visit_VINSERTF32X8(&self, _0: VINSERTF32X8) {}
    fn visit_PACKUSDW(&self, _0: PACKUSDW) {}
    fn visit_VPMOVB2M(&self, _0: VPMOVB2M) {}
    fn visit_WBNOINVD(&self, _0: WBNOINVD) {}
    fn visit_XSAVEOPT(&self, _0: XSAVEOPT) {}
    fn visit_VPABSW(&self, _0: VPABSW) {}
    fn visit_VUNPCKHPD(&self, _0: VUNPCKHPD) {}
    fn visit_VGATHERDPD(&self, _0: VGATHERDPD) {}
    fn visit_VPABSQ(&self, _0: VPABSQ) {}
    fn visit_VPMOVZXBD(&self, _0: VPMOVZXBD) {}
    fn visit_VRSQRT14PD(&self, _0: VRSQRT14PD) {}
    fn visit_XCRYPTECB(&self, _0: XCRYPTECB) {}
    fn visit_VPSHAW(&self, _0: VPSHAW) {}
    fn visit_MOVSQ(&self, _0: MOVSQ) {}
    fn visit_VREDUCEPD(&self, _0: VREDUCEPD) {}
    fn visit_VROUNDPS(&self, _0: VROUNDPS) {}
    fn visit_VDIVPS(&self, _0: VDIVPS) {}
    fn visit_MPSADBW(&self, _0: MPSADBW) {}
    fn visit_VDIVPD(&self, _0: VDIVPD) {}
    fn visit_PAVGW(&self, _0: PAVGW) {}
    fn visit_SHLX(&self, _0: SHLX) {}
    fn visit_CMPXCHG8B(&self, _0: CMPXCHG8B) {}
    fn visit_VFMADD132PS(&self, _0: VFMADD132PS) {}
    fn visit_DEC(&self, _0: DEC) {}
    fn visit_LEA(&self, _0: LEA) {}
    fn visit_PCMPISTRI(&self, _0: PCMPISTRI) {}
    fn visit_KSHIFTRQ(&self, _0: KSHIFTRQ) {}
    fn visit_VCVTPH2PS(&self, _0: VCVTPH2PS) {}
    fn visit_VPMOVSDB(&self, _0: VPMOVSDB) {}
    fn visit_VPHADDWQ(&self, _0: VPHADDWQ) {}
    fn visit_CLZERO(&self, _0: CLZERO) {}
    fn visit_CMOVNBE(&self, _0: CMOVNBE) {}
    fn visit_PUNPCKLQDQ(&self, _0: PUNPCKLQDQ) {}
    fn visit_CLC(&self, _0: CLC) {}
    fn visit_AESDEC(&self, _0: AESDEC) {}
    fn visit_VFMSUB132PS(&self, _0: VFMSUB132PS) {}
    fn visit_V4FNMADDPS(&self, _0: V4FNMADDPS) {}
    fn visit_VPERMPS(&self, _0: VPERMPS) {}
    fn visit_DAA(&self, _0: DAA) {}
    fn visit_VMCLEAR(&self, _0: VMCLEAR) {}
    fn visit_MOVHLPS(&self, _0: MOVHLPS) {}
    fn visit_VPCMPGTB(&self, _0: VPCMPGTB) {}
    fn visit_VUNPCKHPS(&self, _0: VUNPCKHPS) {}
    fn visit_XOR(&self, _0: XOR) {}
    fn visit_CVTTPS2DQ(&self, _0: CVTTPS2DQ) {}
    fn visit_VSHUFI32X4(&self, _0: VSHUFI32X4) {}
    fn visit_SUBSS(&self, _0: SUBSS) {}
    fn visit_JNP(&self, _0: JNP) {}
    fn visit_VMASKMOVPD(&self, _0: VMASKMOVPD) {}
    fn visit_VPRORVD(&self, _0: VPRORVD) {}
    fn visit_VPMINUW(&self, _0: VPMINUW) {}
    fn visit_VMINPD(&self, _0: VMINPD) {}
    fn visit_VPMOVW2M(&self, _0: VPMOVW2M) {}
    fn visit_PSLLQ(&self, _0: PSLLQ) {}
    fn visit_VPCMPISTRM(&self, _0: VPCMPISTRM) {}
    fn visit_SETS(&self, _0: SETS) {}
    fn visit_INVEPT(&self, _0: INVEPT) {}
    fn visit_VPHADDDQ(&self, _0: VPHADDDQ) {}
    fn visit_VADDSUBPD(&self, _0: VADDSUBPD) {}
    fn visit_VPERMW(&self, _0: VPERMW) {}
    fn visit_VPSHRDD(&self, _0: VPSHRDD) {}
    fn visit_VRANGESS(&self, _0: VRANGESS) {}
    fn visit_UCOMISD(&self, _0: UCOMISD) {}
    fn visit_CVTSD2SI(&self, _0: CVTSD2SI) {}
    fn visit_VFNMADD213SD(&self, _0: VFNMADD213SD) {}
    fn visit_VCVTTPS2UQQ(&self, _0: VCVTTPS2UQQ) {}
    fn visit_TEST(&self, _0: TEST) {}
    fn visit_MOVSS(&self, _0: MOVSS) {}
    fn visit_JNO(&self, _0: JNO) {}
    fn visit_VCVTPS2PD(&self, _0: VCVTPS2PD) {}
    fn visit_VPERMI2B(&self, _0: VPERMI2B) {}
    fn visit_CLI(&self, _0: CLI) {}
    fn visit_PINSRW(&self, _0: PINSRW) {}
    fn visit_WRSSQ(&self, _0: WRSSQ) {}
    fn visit_KXORD(&self, _0: KXORD) {}
    fn visit_VEXP2PS(&self, _0: VEXP2PS) {}
    fn visit_VPUNPCKHDQ(&self, _0: VPUNPCKHDQ) {}
    fn visit_BLCMSK(&self, _0: BLCMSK) {}
    fn visit_VPTESTMW(&self, _0: VPTESTMW) {}
    fn visit_VPBLENDVB(&self, _0: VPBLENDVB) {}
    fn visit_VPMOVSQB(&self, _0: VPMOVSQB) {}
    fn visit_VXORPD(&self, _0: VXORPD) {}
    fn visit_BLENDPD(&self, _0: BLENDPD) {}
    fn visit_VPSHAB(&self, _0: VPSHAB) {}
    fn visit_MOVMSKPD(&self, _0: MOVMSKPD) {}
    fn visit_COMISS(&self, _0: COMISS) {}
    fn visit_PMAXSW(&self, _0: PMAXSW) {}
    fn visit_SFENCE(&self, _0: SFENCE) {}
    fn visit_PINSRD(&self, _0: PINSRD) {}
    fn visit_VMOVAPS(&self, _0: VMOVAPS) {}
    fn visit_KUNPCKDQ(&self, _0: KUNPCKDQ) {}
    fn visit_VMOVDQA(&self, _0: VMOVDQA) {}
    fn visit_VGATHERPF1QPS(&self, _0: VGATHERPF1QPS) {}
    fn visit_JCXZ(&self, _0: JCXZ) {}
    fn visit_RDTSC(&self, _0: RDTSC) {}
    fn visit_VPCOMD(&self, _0: VPCOMD) {}
    fn visit_VPMACSSWD(&self, _0: VPMACSSWD) {}
    fn visit_VMAXPS(&self, _0: VMAXPS) {}
    fn visit_VCVTPS2UDQ(&self, _0: VCVTPS2UDQ) {}
    fn visit_WRUSSQ(&self, _0: WRUSSQ) {}
    fn visit_PACKSSWB(&self, _0: PACKSSWB) {}
    fn visit_VADDSUBPS(&self, _0: VADDSUBPS) {}
    fn visit_VPCMPEQB(&self, _0: VPCMPEQB) {}
    fn visit_VFMSUB213SD(&self, _0: VFMSUB213SD) {}
    fn visit_VCVTUSI2SS(&self, _0: VCVTUSI2SS) {}
    fn visit_VEXTRACTF32X4(&self, _0: VEXTRACTF32X4) {}
    fn visit_FCMOVBE(&self, _0: FCMOVBE) {}
    fn visit_VPCMPESTRI(&self, _0: VPCMPESTRI) {}
    fn visit_VPMAXSQ(&self, _0: VPMAXSQ) {}
    fn visit_FINCSTP(&self, _0: FINCSTP) {}
    fn visit_HRESET(&self, _0: HRESET) {}
    fn visit_FDIVP(&self, _0: FDIVP) {}
    fn visit_AESENCWIDE128KL(&self, _0: AESENCWIDE128KL) {}
    fn visit_FXAM(&self, _0: FXAM) {}
    fn visit_LSL(&self, _0: LSL) {}
    fn visit_VPGATHERQQ(&self, _0: VPGATHERQQ) {}
    fn visit_VPLZCNTD(&self, _0: VPLZCNTD) {}
    fn visit_ENCLU(&self, _0: ENCLU) {}
    fn visit_VBROADCASTF32X2(&self, _0: VBROADCASTF32X2) {}
    fn visit_SHA1NEXTE(&self, _0: SHA1NEXTE) {}
    fn visit_PMAXSD(&self, _0: PMAXSD) {}
    fn visit_VMWRITE(&self, _0: VMWRITE) {}
    fn visit_VPSHRDW(&self, _0: VPSHRDW) {}
    fn visit_TPAUSE(&self, _0: TPAUSE) {}
    fn visit_RDTSCP(&self, _0: RDTSCP) {}
    fn visit_VFNMADD231SS(&self, _0: VFNMADD231SS) {}
    fn visit_CLD(&self, _0: CLD) {}
    fn visit_LES(&self, _0: LES) {}
    fn visit_PREFETCHWT1(&self, _0: PREFETCHWT1) {}
    fn visit_PMINUW(&self, _0: PMINUW) {}
    fn visit_VPCOMPRESSD(&self, _0: VPCOMPRESSD) {}
    fn visit_VCVTPD2PS(&self, _0: VCVTPD2PS) {}
    fn visit_PMULHRSW(&self, _0: PMULHRSW) {}
    fn visit_VPMOVZXDQ(&self, _0: VPMOVZXDQ) {}
    fn visit_KADDB(&self, _0: KADDB) {}
    fn visit_VSCATTERPF0DPS(&self, _0: VSCATTERPF0DPS) {}
    fn visit_VPUNPCKLQDQ(&self, _0: VPUNPCKLQDQ) {}
    fn visit_FSTP(&self, _0: FSTP) {}
    fn visit_VPERMILPD(&self, _0: VPERMILPD) {}
    fn visit_VCVTSD2SI(&self, _0: VCVTSD2SI) {}
    fn visit_VBROADCASTF32X8(&self, _0: VBROADCASTF32X8) {}
    fn visit_VRCP28PD(&self, _0: VRCP28PD) {}
    fn visit_SETP(&self, _0: SETP) {}
    fn visit_PUSHFD(&self, _0: PUSHFD) {}
    fn visit_BNDMOV(&self, _0: BNDMOV) {}
    fn visit_INVLPG(&self, _0: INVLPG) {}
    fn visit_ADDPD(&self, _0: ADDPD) {}
    fn visit_VGF2P8MULB(&self, _0: VGF2P8MULB) {}
    fn visit_VUNPCKLPD(&self, _0: VUNPCKLPD) {}
    fn visit_ENDBR32(&self, _0: ENDBR32) {}
    fn visit_ORPS(&self, _0: ORPS) {}
    fn visit_VPADDB(&self, _0: VPADDB) {}
    fn visit_VPBROADCASTB(&self, _0: VPBROADCASTB) {}
    fn visit_XORPS(&self, _0: XORPS) {}
    fn visit_CVTSD2SS(&self, _0: CVTSD2SS) {}
    fn visit_FXRSTOR(&self, _0: FXRSTOR) {}
    fn visit_ROL(&self, _0: ROL) {}
    fn visit_VPMAXSW(&self, _0: VPMAXSW) {}
    fn visit_VPERMT2D(&self, _0: VPERMT2D) {}
    fn visit_VPADDW(&self, _0: VPADDW) {}
    fn visit_PSHUFW(&self, _0: PSHUFW) {}
    fn visit_VPEXPANDD(&self, _0: VPEXPANDD) {}
    fn visit_VPMOVUSDB(&self, _0: VPMOVUSDB) {}
    fn visit_VPTEST(&self, _0: VPTEST) {}
    fn visit_FCMOVE(&self, _0: FCMOVE) {}
    fn visit_SHRX(&self, _0: SHRX) {}
    fn visit_MONITOR(&self, _0: MONITOR) {}
    fn visit_PHADDSW(&self, _0: PHADDSW) {}
    fn visit_VSCATTERQPS(&self, _0: VSCATTERQPS) {}
    fn visit_PREFETCHT0(&self, _0: PREFETCHT0) {}
    fn visit_VRSQRT14PS(&self, _0: VRSQRT14PS) {}
    fn visit_UNPCKHPD(&self, _0: UNPCKHPD) {}
    fn visit_SHA256MSG2(&self, _0: SHA256MSG2) {}
    fn visit_VINSERTI128(&self, _0: VINSERTI128) {}
    fn visit_VREDUCESS(&self, _0: VREDUCESS) {}
    fn visit_PTWRITE(&self, _0: PTWRITE) {}
    fn visit_VPROTQ(&self, _0: VPROTQ) {}
    fn visit_VSCALEFPD(&self, _0: VSCALEFPD) {}
    fn visit_INCSSPQ(&self, _0: INCSSPQ) {}
    fn visit_CRC32(&self, _0: CRC32) {}
    fn visit_VPMOVSXBD(&self, _0: VPMOVSXBD) {}
    fn visit_VPSHRDQ(&self, _0: VPSHRDQ) {}
    fn visit_FCOMIP(&self, _0: FCOMIP) {}
    fn visit_PI2FD(&self, _0: PI2FD) {}
    fn visit_VFNMSUBSD(&self, _0: VFNMSUBSD) {}
    fn visit_VPBLENDW(&self, _0: VPBLENDW) {}
    fn visit_KUNPCKBW(&self, _0: KUNPCKBW) {}
    fn visit_VDPBF16PS(&self, _0: VDPBF16PS) {}
    fn visit_MINSD(&self, _0: MINSD) {}
    fn visit_PEXTRW(&self, _0: PEXTRW) {}
    fn visit_BLENDVPS(&self, _0: BLENDVPS) {}
    fn visit_BLCS(&self, _0: BLCS) {}
    fn visit_ANDPS(&self, _0: ANDPS) {}
    fn visit_VRCPSS(&self, _0: VRCPSS) {}
    fn visit_VPCMPB(&self, _0: VPCMPB) {}
    fn visit_VCVTTPD2UQQ(&self, _0: VCVTTPD2UQQ) {}
    fn visit_VCVTUDQ2PS(&self, _0: VCVTUDQ2PS) {}
    fn visit_VBROADCASTI32X4(&self, _0: VBROADCASTI32X4) {}
    fn visit_MAXSS(&self, _0: MAXSS) {}
    fn visit_STOSB(&self, _0: STOSB) {}
    fn visit_FSTPNCE(&self, _0: FSTPNCE) {}
    fn visit_FABS(&self, _0: FABS) {}
    fn visit_VADDSS(&self, _0: VADDSS) {}
    fn visit_SQRTPD(&self, _0: SQRTPD) {}
    fn visit_MOVNTPD(&self, _0: MOVNTPD) {}
    fn visit_VPSHLQ(&self, _0: VPSHLQ) {}
    fn visit_VPPERM(&self, _0: VPPERM) {}
    fn visit_KANDNB(&self, _0: KANDNB) {}
    fn visit_VCVTUSI2SD(&self, _0: VCVTUSI2SD) {}
    fn visit_XSAVES(&self, _0: XSAVES) {}
    fn visit_VPSRAD(&self, _0: VPSRAD) {}
    fn visit_VPCMPD(&self, _0: VPCMPD) {}
    fn visit_ANDNPD(&self, _0: ANDNPD) {}
    fn visit_PUNPCKHQDQ(&self, _0: PUNPCKHQDQ) {}
    fn visit_STMXCSR(&self, _0: STMXCSR) {}
    fn visit_PMOVZXWD(&self, _0: PMOVZXWD) {}
    fn visit_VPSCATTERQQ(&self, _0: VPSCATTERQQ) {}
    fn visit_VRANGEPS(&self, _0: VRANGEPS) {}
    fn visit_TDPBF16PS(&self, _0: TDPBF16PS) {}
    fn visit_FCHS(&self, _0: FCHS) {}
    fn visit_VGATHERQPD(&self, _0: VGATHERQPD) {}
    fn visit_VSCATTERQPD(&self, _0: VSCATTERQPD) {}
    fn visit_VPCOMPRESSB(&self, _0: VPCOMPRESSB) {}
    fn visit_ROUNDPD(&self, _0: ROUNDPD) {}
    fn visit_XTEST(&self, _0: XTEST) {}
    fn visit_VPMOVDW(&self, _0: VPMOVDW) {}
    fn visit_RDSEED(&self, _0: RDSEED) {}
    fn visit_VFNMSUB132SS(&self, _0: VFNMSUB132SS) {}
    fn visit_MOVNTSS(&self, _0: MOVNTSS) {}
    fn visit_VPHADDUBW(&self, _0: VPHADDUBW) {}
    fn visit_ENTER(&self, _0: ENTER) {}
    fn visit_FWAIT(&self, _0: FWAIT) {}
    fn visit_ADD(&self, _0: ADD) {}
    fn visit_VERW(&self, _0: VERW) {}
    fn visit_JRCXZ(&self, _0: JRCXZ) {}
    fn visit_BLENDPS(&self, _0: BLENDPS) {}
    fn visit_XSHA1(&self, _0: XSHA1) {}
    fn visit_PFNACC(&self, _0: PFNACC) {}
    fn visit_VPCOMUW(&self, _0: VPCOMUW) {}
    fn visit_VMOVQ(&self, _0: VMOVQ) {}
    fn visit_VPSHUFB(&self, _0: VPSHUFB) {}
    fn visit_VPCMPESTRM(&self, _0: VPCMPESTRM) {}
    fn visit_MOVSX(&self, _0: MOVSX) {}
    fn visit_TILELOADD(&self, _0: TILELOADD) {}
    fn visit_V4FNMADDSS(&self, _0: V4FNMADDSS) {}
    fn visit_VPABSB(&self, _0: VPABSB) {}
    fn visit_VMOVDQA64(&self, _0: VMOVDQA64) {}
    fn visit_VPMACSSDQH(&self, _0: VPMACSSDQH) {}
    fn visit_PUNPCKLBW(&self, _0: PUNPCKLBW) {}
    fn visit_RORX(&self, _0: RORX) {}
    fn visit_VPTESTMB(&self, _0: VPTESTMB) {}
    fn visit_XCRYPTCBC(&self, _0: XCRYPTCBC) {}
    fn visit_CMOVZ(&self, _0: CMOVZ) {}
    fn visit_PSIGNW(&self, _0: PSIGNW) {}
    fn visit_VPMOVUSQB(&self, _0: VPMOVUSQB) {}
    fn visit_ADDPS(&self, _0: ADDPS) {}
    fn visit_MOVSD(&self, _0: MOVSD) {}
    fn visit_CMPPD(&self, _0: CMPPD) {}
    fn visit_VEXPANDPD(&self, _0: VEXPANDPD) {}
    fn visit_KANDD(&self, _0: KANDD) {}
    fn visit_TILESTORED(&self, _0: TILESTORED) {}
    fn visit_VEXTRACTI32X4(&self, _0: VEXTRACTI32X4) {}
    fn visit_AAM(&self, _0: AAM) {}
    fn visit_VPSHLD(&self, _0: VPSHLD) {}
    fn visit_STUI(&self, _0: STUI) {}
    fn visit_VPEXPANDB(&self, _0: VPEXPANDB) {}
    fn visit_VFNMSUB231SD(&self, _0: VFNMSUB231SD) {}
    fn visit_FSETPM287_NOP(&self, _0: FSETPM287_NOP) {}
    fn visit_RDRAND(&self, _0: RDRAND) {}
    fn visit_XSAVE(&self, _0: XSAVE) {}
    fn visit_VPUNPCKHWD(&self, _0: VPUNPCKHWD) {}
    fn visit_VMCALL(&self, _0: VMCALL) {}
    fn visit_MOVDQU(&self, _0: MOVDQU) {}
    fn visit_SETNL(&self, _0: SETNL) {}
    fn visit_PSUBQ(&self, _0: PSUBQ) {}
    fn visit_VGETEXPPS(&self, _0: VGETEXPPS) {}
    fn visit_VPROLVD(&self, _0: VPROLVD) {}
    fn visit_VSCALEFSS(&self, _0: VSCALEFSS) {}
    fn visit_FSUB(&self, _0: FSUB) {}
    fn visit_FNSAVE(&self, _0: FNSAVE) {}
    fn visit_UD2(&self, _0: UD2) {}
    fn visit_VPMASKMOVQ(&self, _0: VPMASKMOVQ) {}
    fn visit_TDPBUSD(&self, _0: TDPBUSD) {}
    fn visit_VCVTUDQ2PD(&self, _0: VCVTUDQ2PD) {}
    fn visit_VPTESTMQ(&self, _0: VPTESTMQ) {}
    fn visit_VANDNPS(&self, _0: VANDNPS) {}
    fn visit_VPMULLQ(&self, _0: VPMULLQ) {}
    fn visit_VPRORVQ(&self, _0: VPRORVQ) {}
    fn visit_VMOVHPS(&self, _0: VMOVHPS) {}
    fn visit_PCMPESTRM(&self, _0: PCMPESTRM) {}
    fn visit_VPMACSWD(&self, _0: VPMACSWD) {}
    fn visit_LDDQU(&self, _0: LDDQU) {}
    fn visit_VPHSUBSW(&self, _0: VPHSUBSW) {}
    fn visit_PMINUB(&self, _0: PMINUB) {}
    fn visit_AESENC128KL(&self, _0: AESENC128KL) {}
    fn visit_SETNB(&self, _0: SETNB) {}
    fn visit_PSUBSW(&self, _0: PSUBSW) {}
    fn visit_VFNMSUB132PS(&self, _0: VFNMSUB132PS) {}
    fn visit_KXORB(&self, _0: KXORB) {}
    fn visit_VMOVDQU16(&self, _0: VMOVDQU16) {}
    fn visit_AAD(&self, _0: AAD) {}
    fn visit_PSIGND(&self, _0: PSIGND) {}
    fn visit_VCOMISS(&self, _0: VCOMISS) {}
    fn visit_UNPCKLPD(&self, _0: UNPCKLPD) {}
    fn visit_PMOVSXWD(&self, _0: PMOVSXWD) {}
    fn visit_VPAVGW(&self, _0: VPAVGW) {}
    fn visit_SWAPGS(&self, _0: SWAPGS) {}
    fn visit_MASKMOVDQU(&self, _0: MASKMOVDQU) {}
    fn visit_CMOVLE(&self, _0: CMOVLE) {}
    fn visit_MINSS(&self, _0: MINSS) {}
    fn visit_SHRD(&self, _0: SHRD) {}
    fn visit_PMOVSXBQ(&self, _0: PMOVSXBQ) {}
    fn visit_VPCOMUD(&self, _0: VPCOMUD) {}
    fn visit_VPMULUDQ(&self, _0: VPMULUDQ) {}
    fn visit_VPMAXUW(&self, _0: VPMAXUW) {}
    fn visit_VFNMADD231SD(&self, _0: VFNMADD231SD) {}
    fn visit_VUCOMISS(&self, _0: VUCOMISS) {}
    fn visit_VPMOVMSKB(&self, _0: VPMOVMSKB) {}
    fn visit_VFNMSUB213PS(&self, _0: VFNMSUB213PS) {}
    fn visit_PSRAD(&self, _0: PSRAD) {}
    fn visit_PREFETCHNTA(&self, _0: PREFETCHNTA) {}
    fn visit_PUSHA(&self, _0: PUSHA) {}
    fn visit_VPMOVM2B(&self, _0: VPMOVM2B) {}
    fn visit_VGATHERDPS(&self, _0: VGATHERDPS) {}
    fn visit_VP2INTERSECTQ(&self, _0: VP2INTERSECTQ) {}
    fn visit_VPMACSDQL(&self, _0: VPMACSDQL) {}
    fn visit_VFMADDPD(&self, _0: VFMADDPD) {}
    fn visit_VPMOVSXBW(&self, _0: VPMOVSXBW) {}
    fn visit_FNSTCW(&self, _0: FNSTCW) {}
    fn visit_VPMULLD(&self, _0: VPMULLD) {}
    fn visit_VPCMPEQD(&self, _0: VPCMPEQD) {}
    fn visit_VPALIGNR(&self, _0: VPALIGNR) {}
    fn visit_EXTRQ(&self, _0: EXTRQ) {}
    fn visit_CVTPD2PS(&self, _0: CVTPD2PS) {}
    fn visit_VPTESTNMB(&self, _0: VPTESTNMB) {}
    fn visit_POPCNT(&self, _0: POPCNT) {}
    fn visit_VFMSUBADDPS(&self, _0: VFMSUBADDPS) {}
    fn visit_VPUNPCKLWD(&self, _0: VPUNPCKLWD) {}
    fn visit_AND(&self, _0: AND) {}
    fn visit_CLTS(&self, _0: CLTS) {}
    fn visit_SLDT(&self, _0: SLDT) {}
    fn visit_PCMPEQD(&self, _0: PCMPEQD) {}
    fn visit_CLWB(&self, _0: CLWB) {}
    fn visit_VPBROADCASTW(&self, _0: VPBROADCASTW) {}
    fn visit_VPERM2F128(&self, _0: VPERM2F128) {}
    fn visit_KORD(&self, _0: KORD) {}
    fn visit_VGATHERPF1DPS(&self, _0: VGATHERPF1DPS) {}
    fn visit_PMOVZXBW(&self, _0: PMOVZXBW) {}
    fn visit_XRSTORS64(&self, _0: XRSTORS64) {}
    fn visit_VMINSD(&self, _0: VMINSD) {}
    fn visit_VPMOVM2W(&self, _0: VPMOVM2W) {}
    fn visit_MOVDDUP(&self, _0: MOVDDUP) {}
    fn visit_JP(&self, _0: JP) {}
    fn visit_VFNMADD231PD(&self, _0: VFNMADD231PD) {}
    fn visit_PMOVSXBD(&self, _0: PMOVSXBD) {}
    fn visit_LODSQ(&self, _0: LODSQ) {}
    fn visit_PCMPEQW(&self, _0: PCMPEQW) {}
    fn visit_CMOVL(&self, _0: CMOVL) {}
    fn visit_BSR(&self, _0: BSR) {}
    fn visit_VPMACSWW(&self, _0: VPMACSWW) {}
    fn visit_BLCI(&self, _0: BLCI) {}
    fn visit_VRCP28PS(&self, _0: VRCP28PS) {}
    fn visit_VCVTPD2QQ(&self, _0: VCVTPD2QQ) {}
    fn visit_FDECSTP(&self, _0: FDECSTP) {}
    fn visit_VBROADCASTF128(&self, _0: VBROADCASTF128) {}
    fn visit_PSRLDQ(&self, _0: PSRLDQ) {}
    fn visit_VPSLLD(&self, _0: VPSLLD) {}
    fn visit_BTR(&self, _0: BTR) {}
    fn visit_DIVPD(&self, _0: DIVPD) {}
    fn visit_VPGATHERQD(&self, _0: VPGATHERQD) {}
    fn visit_VPMOVSQD(&self, _0: VPMOVSQD) {}
    fn visit_VFMADDSUB213PD(&self, _0: VFMADDSUB213PD) {}
    fn visit_XSHA256(&self, _0: XSHA256) {}
    fn visit_VPINSRW(&self, _0: VPINSRW) {}
    fn visit_PREFETCHW(&self, _0: PREFETCHW) {}
    fn visit_INCSSPD(&self, _0: INCSSPD) {}
    fn visit_VFNMADDPD(&self, _0: VFNMADDPD) {}
    fn visit_SCASW(&self, _0: SCASW) {}
    fn visit_VBROADCASTF32X4(&self, _0: VBROADCASTF32X4) {}
    fn visit_KSHIFTRB(&self, _0: KSHIFTRB) {}
    fn visit_PSHUFHW(&self, _0: PSHUFHW) {}
    fn visit_PCMPEQQ(&self, _0: PCMPEQQ) {}
    fn visit_VSCALEFPS(&self, _0: VSCALEFPS) {}
    fn visit_VGETMANTPS(&self, _0: VGETMANTPS) {}
    fn visit_SGDT(&self, _0: SGDT) {}
    fn visit_VANDNPD(&self, _0: VANDNPD) {}
    fn visit_MOVD(&self, _0: MOVD) {}
    fn visit_VPADDUSB(&self, _0: VPADDUSB) {}
    fn visit_TZMSK(&self, _0: TZMSK) {}
    fn visit_VPMULLW(&self, _0: VPMULLW) {}
    fn visit_VMPTRLD(&self, _0: VMPTRLD) {}
    fn visit_MASKMOVQ(&self, _0: MASKMOVQ) {}
    fn visit_AESENC(&self, _0: AESENC) {}
    fn visit_FMULP(&self, _0: FMULP) {}
    fn visit_PCMPEQB(&self, _0: PCMPEQB) {}
    fn visit_VPHADDW(&self, _0: VPHADDW) {}
    fn visit_VRSQRTSS(&self, _0: VRSQRTSS) {}
    fn visit_VFMSUBADD231PD(&self, _0: VFMSUBADD231PD) {}
    fn visit_VPDPWSSD(&self, _0: VPDPWSSD) {}
    fn visit_VFMADD231SD(&self, _0: VFMADD231SD) {}
    fn visit_LDTILECFG(&self, _0: LDTILECFG) {}
    fn visit_VSCATTERPF1QPS(&self, _0: VSCATTERPF1QPS) {}
    fn visit_IRETQ(&self, _0: IRETQ) {}
    fn visit_VGETMANTPD(&self, _0: VGETMANTPD) {}
    fn visit_KSHIFTLQ(&self, _0: KSHIFTLQ) {}
    fn visit_VCVTPD2UQQ(&self, _0: VCVTPD2UQQ) {}
    fn visit_VCVTTPD2QQ(&self, _0: VCVTTPD2QQ) {}
    fn visit_VEXTRACTF32X8(&self, _0: VEXTRACTF32X8) {}
    fn visit_VMOVSHDUP(&self, _0: VMOVSHDUP) {}
    fn visit_XSAVEOPT64(&self, _0: XSAVEOPT64) {}
    fn visit_XSAVE64(&self, _0: XSAVE64) {}
    fn visit_FICOMP(&self, _0: FICOMP) {}
    fn visit_VPHADDUWQ(&self, _0: VPHADDUWQ) {}
    fn visit_PMINSB(&self, _0: PMINSB) {}
    fn visit_MOVUPD(&self, _0: MOVUPD) {}
    fn visit_INSERTQ(&self, _0: INSERTQ) {}
    fn visit_MOVBE(&self, _0: MOVBE) {}
    fn visit_SCASD(&self, _0: SCASD) {}
    fn visit_VCVTTPD2DQ(&self, _0: VCVTTPD2DQ) {}
    fn visit_VPMADDWD(&self, _0: VPMADDWD) {}
    fn visit_POR(&self, _0: POR) {}
    fn visit_VPCMPISTRI(&self, _0: VPCMPISTRI) {}
    fn visit_VFNMADD132SS(&self, _0: VFNMADD132SS) {}
    fn visit_VPSCATTERDQ(&self, _0: VPSCATTERDQ) {}
    fn visit_VPSRAVD(&self, _0: VPSRAVD) {}
    fn visit_CMPSW(&self, _0: CMPSW) {}
    fn visit_CMOVNS(&self, _0: CMOVNS) {}
    fn visit_FSIN(&self, _0: FSIN) {}
    fn visit_TESTUI(&self, _0: TESTUI) {}
    fn visit_VPSHAD(&self, _0: VPSHAD) {}
    fn visit_UMWAIT(&self, _0: UMWAIT) {}
    fn visit_KADDD(&self, _0: KADDD) {}
    fn visit_LLDT(&self, _0: LLDT) {}
    fn visit_VPSHUFLW(&self, _0: VPSHUFLW) {}
    fn visit_VPCOMPRESSQ(&self, _0: VPCOMPRESSQ) {}
    fn visit_VMOVMSKPS(&self, _0: VMOVMSKPS) {}
    fn visit_PMOVSXDQ(&self, _0: PMOVSXDQ) {}
    fn visit_FCMOVNE(&self, _0: FCMOVNE) {}
    fn visit_BLSMSK(&self, _0: BLSMSK) {}
    fn visit_VSCATTERPF0DPD(&self, _0: VSCATTERPF0DPD) {}
    fn visit_VPUNPCKLDQ(&self, _0: VPUNPCKLDQ) {}
    fn visit_VP4DPWSSD(&self, _0: VP4DPWSSD) {}
    fn visit_VPBROADCASTMW2D(&self, _0: VPBROADCASTMW2D) {}
    fn visit_VRANGEPD(&self, _0: VRANGEPD) {}
    fn visit_VPMADD52HUQ(&self, _0: VPMADD52HUQ) {}
    fn visit_PMINSD(&self, _0: PMINSD) {}
    fn visit_VADDPD(&self, _0: VADDPD) {}
    fn visit_VPSHRDVQ(&self, _0: VPSHRDVQ) {}
    fn visit_WRPKRU(&self, _0: WRPKRU) {}
    fn visit_PMINUD(&self, _0: PMINUD) {}
    fn visit_ADCX(&self, _0: ADCX) {}
    fn visit_NOT(&self, _0: NOT) {}
    fn visit_RCPPS(&self, _0: RCPPS) {}
    fn visit_VREDUCEPS(&self, _0: VREDUCEPS) {}
    fn visit_INVALID(&self, _0: INVALID) {}
    fn visit_WRSSD(&self, _0: WRSSD) {}
    fn visit_MOVMSKPS(&self, _0: MOVMSKPS) {}
    fn visit_JB(&self, _0: JB) {}
    fn visit_SKINIT(&self, _0: SKINIT) {}
    fn visit_TDPBSUD(&self, _0: TDPBSUD) {}
    fn visit_FLDENV(&self, _0: FLDENV) {}
    fn visit_PEXTRB(&self, _0: PEXTRB) {}
    fn visit_FSINCOS(&self, _0: FSINCOS) {}
    fn visit_VPINSRD(&self, _0: VPINSRD) {}
    fn visit_FCMOVNBE(&self, _0: FCMOVNBE) {}
    fn visit_VPMAXSD(&self, _0: VPMAXSD) {}
    fn visit_VPINSRQ(&self, _0: VPINSRQ) {}
    fn visit_KORQ(&self, _0: KORQ) {}
    fn visit_CVTTSS2SI(&self, _0: CVTTSS2SI) {}
    fn visit_CMOVNLE(&self, _0: CMOVNLE) {}
    fn visit_FFREEP(&self, _0: FFREEP) {}
    fn visit_CMP(&self, _0: CMP) {}
    fn visit_CVTPI2PD(&self, _0: CVTPI2PD) {}
    fn visit_CLGI(&self, _0: CLGI) {}
    fn visit_VFNMADDSS(&self, _0: VFNMADDSS) {}
    fn visit_VFNMSUBSS(&self, _0: VFNMSUBSS) {}
    fn visit_VCVTSI2SD(&self, _0: VCVTSI2SD) {}
    fn visit_CVTPS2PD(&self, _0: CVTPS2PD) {}
    fn visit_VZEROALL(&self, _0: VZEROALL) {}
    fn visit_FDIVR(&self, _0: FDIVR) {}
    fn visit_MOVSB(&self, _0: MOVSB) {}
    fn visit_MOVDQA(&self, _0: MOVDQA) {}
    fn visit_FCOMI(&self, _0: FCOMI) {}
    fn visit_CLAC(&self, _0: CLAC) {}
    fn visit_VFMADDPS(&self, _0: VFMADDPS) {}
    fn visit_VSUBSS(&self, _0: VSUBSS) {}
    fn visit_VMLAUNCH(&self, _0: VMLAUNCH) {}
    fn visit_KTESTQ(&self, _0: KTESTQ) {}
    fn visit_VBLENDMPS(&self, _0: VBLENDMPS) {}
    fn visit_VCVTSS2USI(&self, _0: VCVTSS2USI) {}
    fn visit_FICOM(&self, _0: FICOM) {}
    fn visit_VFMADDSUBPD(&self, _0: VFMADDSUBPD) {}
    fn visit_VPROLVQ(&self, _0: VPROLVQ) {}
    fn visit_VCVTUQQ2PS(&self, _0: VCVTUQQ2PS) {}
    fn visit_FISUB(&self, _0: FISUB) {}
    fn visit_VPMOVD2M(&self, _0: VPMOVD2M) {}
    fn visit_VPTESTNMW(&self, _0: VPTESTNMW) {}
    fn visit_VFMSUBPS(&self, _0: VFMSUBPS) {}
    fn visit_VPERMILPS(&self, _0: VPERMILPS) {}
    fn visit_VTESTPD(&self, _0: VTESTPD) {}
    fn visit_VPMACSDD(&self, _0: VPMACSDD) {}
    fn visit_MOVLPS(&self, _0: MOVLPS) {}
    fn visit_VPBLENDMQ(&self, _0: VPBLENDMQ) {}
    fn visit_VPBROADCASTD(&self, _0: VPBROADCASTD) {}
    fn visit_VPCMPUD(&self, _0: VPCMPUD) {}
    fn visit_VPROTD(&self, _0: VPROTD) {}
    fn visit_FPATAN(&self, _0: FPATAN) {}
    fn visit_MINPD(&self, _0: MINPD) {}
    fn visit_VMREAD(&self, _0: VMREAD) {}
    fn visit_PMULLD(&self, _0: PMULLD) {}
    fn visit_VSCATTERPF0QPS(&self, _0: VSCATTERPF0QPS) {}
    fn visit_VMMCALL(&self, _0: VMMCALL) {}
    fn visit_LLWPCB(&self, _0: LLWPCB) {}
    fn visit_VFPCLASSPD(&self, _0: VFPCLASSPD) {}
    fn visit_XLAT(&self, _0: XLAT) {}
    fn visit_PABSB(&self, _0: PABSB) {}
    fn visit_VFMSUBADDPD(&self, _0: VFMSUBADDPD) {}
    fn visit_PUSHFQ(&self, _0: PUSHFQ) {}
    fn visit_VAESKEYGENASSIST(&self, _0: VAESKEYGENASSIST) {}
    fn visit_FADD(&self, _0: FADD) {}
    fn visit_INVPCID(&self, _0: INVPCID) {}
    fn visit_KXNORB(&self, _0: KXNORB) {}
    fn visit_TDCALL(&self, _0: TDCALL) {}
    fn visit_VFMSUB132SS(&self, _0: VFMSUB132SS) {}
    fn visit_FIDIV(&self, _0: FIDIV) {}
    fn visit_FUCOMI(&self, _0: FUCOMI) {}
    fn visit_VSHUFF64X2(&self, _0: VSHUFF64X2) {}
    fn visit_VPDPWSSDS(&self, _0: VPDPWSSDS) {}
    fn visit_FCOM(&self, _0: FCOM) {}
    fn visit_CMPSS(&self, _0: CMPSS) {}
    fn visit_VPMOVM2D(&self, _0: VPMOVM2D) {}
    fn visit_JO(&self, _0: JO) {}
    fn visit_MOVSHDUP(&self, _0: MOVSHDUP) {}
    fn visit_CDQE(&self, _0: CDQE) {}
    fn visit_FST(&self, _0: FST) {}
    fn visit_STOSW(&self, _0: STOSW) {}
    fn visit_VPHSUBDQ(&self, _0: VPHSUBDQ) {}
    fn visit_PSHUFD(&self, _0: PSHUFD) {}
    fn visit_TILEZERO(&self, _0: TILEZERO) {}
    fn visit_PMOVZXBQ(&self, _0: PMOVZXBQ) {}
    fn visit_PAVGUSB(&self, _0: PAVGUSB) {}
    fn visit_FLDZ(&self, _0: FLDZ) {}
    fn visit_VRSQRT28SD(&self, _0: VRSQRT28SD) {}
    fn visit_VPMOVSDW(&self, _0: VPMOVSDW) {}
    fn visit_VPHADDD(&self, _0: VPHADDD) {}
    fn visit_UNPCKLPS(&self, _0: UNPCKLPS) {}
    fn visit_VDPPD(&self, _0: VDPPD) {}
    fn visit_VPSUBUSW(&self, _0: VPSUBUSW) {}
    fn visit_PSUBW(&self, _0: PSUBW) {}
    fn visit_CALL_FAR(&self, _0: CALL_FAR) {}
    fn visit_SHLD(&self, _0: SHLD) {}
    fn visit_VPERMT2B(&self, _0: VPERMT2B) {}
    fn visit_VPHADDBQ(&self, _0: VPHADDBQ) {}
    fn visit_VGF2P8AFFINEQB(&self, _0: VGF2P8AFFINEQB) {}
    fn visit_VEXP2PD(&self, _0: VEXP2PD) {}
    fn visit_KNOTB(&self, _0: KNOTB) {}
    fn visit_VPSHUFHW(&self, _0: VPSHUFHW) {}
    fn visit_VPSUBQ(&self, _0: VPSUBQ) {}
    fn visit_VPTESTMD(&self, _0: VPTESTMD) {}
    fn visit_VPSRAQ(&self, _0: VPSRAQ) {}
    fn visit_VFRCZPS(&self, _0: VFRCZPS) {}
    fn visit_MOVNTPS(&self, _0: MOVNTPS) {}
    fn visit_MOV(&self, _0: MOV) {}
    fn visit_SALC(&self, _0: SALC) {}
    fn visit_FPREM1(&self, _0: FPREM1) {}
    fn visit_VPCOMB(&self, _0: VPCOMB) {}
    fn visit_VTESTPS(&self, _0: VTESTPS) {}
    fn visit_VPMAXUB(&self, _0: VPMAXUB) {}
    fn visit_JLE(&self, _0: JLE) {}
    fn visit_JNZ(&self, _0: JNZ) {}
    fn visit_MUL(&self, _0: MUL) {}
    fn visit_VFRCZSD(&self, _0: VFRCZSD) {}
    fn visit_PFMIN(&self, _0: PFMIN) {}
    fn visit_VPHADDBD(&self, _0: VPHADDBD) {}
    fn visit_VCVTTPS2DQ(&self, _0: VCVTTPS2DQ) {}
    fn visit_VPSUBB(&self, _0: VPSUBB) {}
    fn visit_VPSUBD(&self, _0: VPSUBD) {}
    fn visit_VORPD(&self, _0: VORPD) {}
    fn visit_INVD(&self, _0: INVD) {}
    fn visit_VPMACSSDQL(&self, _0: VPMACSSDQL) {}
    fn visit_VPMINUD(&self, _0: VPMINUD) {}
    fn visit_VMOVSS(&self, _0: VMOVSS) {}
    fn visit_VPEXTRD(&self, _0: VPEXTRD) {}
    fn visit_VMOVNTPD(&self, _0: VMOVNTPD) {}
    fn visit_VMASKMOVDQU(&self, _0: VMASKMOVDQU) {}
    fn visit_VFMADD132PD(&self, _0: VFMADD132PD) {}
    fn visit_PTEST(&self, _0: PTEST) {}
    fn visit_VFMSUB213PS(&self, _0: VFMSUB213PS) {}
    fn visit_FSCALE(&self, _0: FSCALE) {}
    fn visit_UCOMISS(&self, _0: UCOMISS) {}
    fn visit_KORW(&self, _0: KORW) {}
    fn visit_LMSW(&self, _0: LMSW) {}
    fn visit_VPADDQ(&self, _0: VPADDQ) {}
    fn visit_VFMADD231PD(&self, _0: VFMADD231PD) {}
    fn visit_VBROADCASTF64X2(&self, _0: VBROADCASTF64X2) {}
    fn visit_VREDUCESD(&self, _0: VREDUCESD) {}
    fn visit_SLWPCB(&self, _0: SLWPCB) {}
    fn visit_MULPS(&self, _0: MULPS) {}
    fn visit_FCOMPP(&self, _0: FCOMPP) {}
    fn visit_RCL(&self, _0: RCL) {}
    fn visit_PSHUFB(&self, _0: PSHUFB) {}
    fn visit_VPHADDUBD(&self, _0: VPHADDUBD) {}
    fn visit_PBLENDW(&self, _0: PBLENDW) {}
    fn visit_XORPD(&self, _0: XORPD) {}
    fn visit_VPMADCSWD(&self, _0: VPMADCSWD) {}
    fn visit_VMINPS(&self, _0: VMINPS) {}
    fn visit_MAXSD(&self, _0: MAXSD) {}
    fn visit_VPCMPEQQ(&self, _0: VPCMPEQQ) {}
    fn visit_RET_FAR(&self, _0: RET_FAR) {}
    fn visit_VPMAXUD(&self, _0: VPMAXUD) {}
    fn visit_AESENCLAST(&self, _0: AESENCLAST) {}
    fn visit_SEAMCALL(&self, _0: SEAMCALL) {}
    fn visit_VPSRLQ(&self, _0: VPSRLQ) {}
    fn visit_VPMINUB(&self, _0: VPMINUB) {}
    fn visit_LZCNT(&self, _0: LZCNT) {}
    fn visit_KTESTW(&self, _0: KTESTW) {}
    fn visit_PI2FW(&self, _0: PI2FW) {}
    fn visit_VRCP28SS(&self, _0: VRCP28SS) {}
    fn visit_VPCOMUQ(&self, _0: VPCOMUQ) {}
    fn visit_CMOVBE(&self, _0: CMOVBE) {}
    fn visit_VPADDD(&self, _0: VPADDD) {}
    fn visit_VFMADD132SD(&self, _0: VFMADD132SD) {}
    fn visit_VGATHERPF0DPS(&self, _0: VGATHERPF0DPS) {}
    fn visit_FYL2X(&self, _0: FYL2X) {}
    fn visit_PUNPCKLWD(&self, _0: PUNPCKLWD) {}
    fn visit_SBB(&self, _0: SBB) {}
    fn visit_PMOVMSKB(&self, _0: PMOVMSKB) {}
    fn visit_VANDPS(&self, _0: VANDPS) {}
    fn visit_XSETBV(&self, _0: XSETBV) {}
    fn visit_PFCMPGT(&self, _0: PFCMPGT) {}
    fn visit_VCVTSS2SD(&self, _0: VCVTSS2SD) {}
    fn visit_LDS(&self, _0: LDS) {}
    fn visit_VFMADD132SS(&self, _0: VFMADD132SS) {}
    fn visit_FIDIVR(&self, _0: FIDIVR) {}
    fn visit_VRSQRTPS(&self, _0: VRSQRTPS) {}
    fn visit_OR(&self, _0: OR) {}
    fn visit_VPHSUBWD(&self, _0: VPHSUBWD) {}
    fn visit_POPAD(&self, _0: POPAD) {}
    fn visit_VFMSUBADD132PD(&self, _0: VFMSUBADD132PD) {}
    fn visit_VPBLENDD(&self, _0: VPBLENDD) {}
    fn visit_VPMACSDQH(&self, _0: VPMACSDQH) {}
    fn visit_VPXOR(&self, _0: VPXOR) {}
    fn visit_VPGATHERDD(&self, _0: VPGATHERDD) {}
    fn visit_VPROLQ(&self, _0: VPROLQ) {}
    fn visit_VPMADD52LUQ(&self, _0: VPMADD52LUQ) {}
    fn visit_VFPCLASSSD(&self, _0: VFPCLASSSD) {}
    fn visit_DAS(&self, _0: DAS) {}
    fn visit_UMONITOR(&self, _0: UMONITOR) {}
    fn visit_VMXOFF(&self, _0: VMXOFF) {}
    fn visit_VDIVSS(&self, _0: VDIVSS) {}
    fn visit_PMADDWD(&self, _0: PMADDWD) {}
    fn visit_VPMOVZXWD(&self, _0: VPMOVZXWD) {}
    fn visit_JNS(&self, _0: JNS) {}
    fn visit_MOVQ(&self, _0: MOVQ) {}
    fn visit_PMOVSXWQ(&self, _0: PMOVSXWQ) {}
    fn visit_VPSLLVQ(&self, _0: VPSLLVQ) {}
    fn visit_VADDPS(&self, _0: VADDPS) {}
    fn visit_VFRCZPD(&self, _0: VFRCZPD) {}
    fn visit_VINSERTPS(&self, _0: VINSERTPS) {}
    fn visit_VPMOVSWB(&self, _0: VPMOVSWB) {}
    fn visit_LFS(&self, _0: LFS) {}
    fn visit_PUSHAD(&self, _0: PUSHAD) {}
    fn visit_PMOVSXBW(&self, _0: PMOVSXBW) {}
    fn visit_VBROADCASTF64X4(&self, _0: VBROADCASTF64X4) {}
    fn visit_PSMASH(&self, _0: PSMASH) {}
    fn visit_PMAXUB(&self, _0: PMAXUB) {}
    fn visit_KSHIFTRD(&self, _0: KSHIFTRD) {}
    fn visit_CALL(&self, _0: CALL) {}
    fn visit_PMULHUW(&self, _0: PMULHUW) {}
    fn visit_PVALIDATE(&self, _0: PVALIDATE) {}
    fn visit_SETNO(&self, _0: SETNO) {}
    fn visit_SETBE(&self, _0: SETBE) {}
    fn visit_VPMULHW(&self, _0: VPMULHW) {}
    fn visit_VEXTRACTPS(&self, _0: VEXTRACTPS) {}
    fn visit_VINSERTF128(&self, _0: VINSERTF128) {}
    fn visit_VPMINSB(&self, _0: VPMINSB) {}
    fn visit_VPCMPGTD(&self, _0: VPCMPGTD) {}
    fn visit_VMOVHPD(&self, _0: VMOVHPD) {}
    fn visit_VPACKSSWB(&self, _0: VPACKSSWB) {}
    fn visit_VAESIMC(&self, _0: VAESIMC) {}
    fn visit_VFNMADD132SD(&self, _0: VFNMADD132SD) {}
    fn visit_VGF2P8AFFINEINVQB(&self, _0: VGF2P8AFFINEINVQB) {}
    fn visit_VPDPBUSD(&self, _0: VPDPBUSD) {}
    fn visit_SHA1MSG1(&self, _0: SHA1MSG1) {}
    fn visit_KMOVD(&self, _0: KMOVD) {}
    fn visit_VSCATTERPF1DPD(&self, _0: VSCATTERPF1DPD) {}
    fn visit_VPMOVSXWD(&self, _0: VPMOVSXWD) {}
    fn visit_STD(&self, _0: STD) {}
    fn visit_POP(&self, _0: POP) {}
    fn visit_FISTTP(&self, _0: FISTTP) {}
    fn visit_VMOVNTDQA(&self, _0: VMOVNTDQA) {}
    fn visit_VFIXUPIMMPS(&self, _0: VFIXUPIMMPS) {}
    fn visit_LDMXCSR(&self, _0: LDMXCSR) {}
    fn visit_JMP_FAR(&self, _0: JMP_FAR) {}
    fn visit_VRSQRT28SS(&self, _0: VRSQRT28SS) {}
    fn visit_VGETEXPSS(&self, _0: VGETEXPSS) {}
    fn visit_VPTERNLOGD(&self, _0: VPTERNLOGD) {}
    fn visit_SHL(&self, _0: SHL) {}
    fn visit_BT(&self, _0: BT) {}
    fn visit_KORTESTQ(&self, _0: KORTESTQ) {}
    fn visit_VMOVDQU(&self, _0: VMOVDQU) {}
    fn visit_DPPS(&self, _0: DPPS) {}
    fn visit_VPSRLDQ(&self, _0: VPSRLDQ) {}
    fn visit_LODSB(&self, _0: LODSB) {}
    fn visit_FNSTSW(&self, _0: FNSTSW) {}
    fn visit_VGATHERQPS(&self, _0: VGATHERQPS) {}
    fn visit_VPMADCSSWD(&self, _0: VPMADCSSWD) {}
    fn visit_PMOVZXDQ(&self, _0: PMOVZXDQ) {}
    fn visit_VLDMXCSR(&self, _0: VLDMXCSR) {}
    fn visit_VFMADD213PD(&self, _0: VFMADD213PD) {}
    fn visit_PSUBSB(&self, _0: PSUBSB) {}
    fn visit_FILD(&self, _0: FILD) {}
    fn visit_VFMADD231SS(&self, _0: VFMADD231SS) {}
    fn visit_ADDSUBPS(&self, _0: ADDSUBPS) {}
    fn visit_VPSHUFBITQMB(&self, _0: VPSHUFBITQMB) {}
    fn visit_VFNMADD213PS(&self, _0: VFNMADD213PS) {}
    fn visit_CPUID(&self, _0: CPUID) {}
    fn visit_PFSUB(&self, _0: PFSUB) {}
    fn visit_RCPSS(&self, _0: RCPSS) {}
    fn visit_XSTORE(&self, _0: XSTORE) {}
    fn visit_FSUBP(&self, _0: FSUBP) {}
    fn visit_VPSUBSW(&self, _0: VPSUBSW) {}
    fn visit_PMULHRW(&self, _0: PMULHRW) {}
    fn visit_MOVNTDQA(&self, _0: MOVNTDQA) {}
    fn visit_CVTSS2SI(&self, _0: CVTSS2SI) {}
    fn visit_WRUSSD(&self, _0: WRUSSD) {}
    fn visit_BLSIC(&self, _0: BLSIC) {}
    fn visit_PSUBD(&self, _0: PSUBD) {}
    fn visit_VANDPD(&self, _0: VANDPD) {}
    fn visit_VAESENC(&self, _0: VAESENC) {}
    fn visit_VAESDECLAST(&self, _0: VAESDECLAST) {}
    fn visit_RDGSBASE(&self, _0: RDGSBASE) {}
    fn visit_PEXT(&self, _0: PEXT) {}
    fn visit_KSHIFTRW(&self, _0: KSHIFTRW) {}
    fn visit_V4FMADDSS(&self, _0: V4FMADDSS) {}
    fn visit_SYSEXIT(&self, _0: SYSEXIT) {}
    fn visit_CMPPS(&self, _0: CMPPS) {}
    fn visit_LTR(&self, _0: LTR) {}
    fn visit_CBW(&self, _0: CBW) {}
    fn visit_VPCMPGTQ(&self, _0: VPCMPGTQ) {}
    fn visit_MOVDIRI(&self, _0: MOVDIRI) {}
    fn visit_KADDQ(&self, _0: KADDQ) {}
    fn visit_VPHADDUDQ(&self, _0: VPHADDUDQ) {}
    fn visit_VCVTNEPS2BF16(&self, _0: VCVTNEPS2BF16) {}
    fn visit_VSCATTERPF1QPD(&self, _0: VSCATTERPF1QPD) {}
    fn visit_VCVTTSD2USI(&self, _0: VCVTTSD2USI) {}
    fn visit_VRNDSCALEPS(&self, _0: VRNDSCALEPS) {}
    fn visit_VSCALEFSD(&self, _0: VSCALEFSD) {}
    fn visit_VCVTPS2UQQ(&self, _0: VCVTPS2UQQ) {}
    fn visit_VPMOVUSWB(&self, _0: VPMOVUSWB) {}
    fn visit_VPERMB(&self, _0: VPERMB) {}
    fn visit_CVTDQ2PD(&self, _0: CVTDQ2PD) {}
    fn visit_CMOVS(&self, _0: CMOVS) {}
    fn visit_VXORPS(&self, _0: VXORPS) {}
    fn visit_AESKEYGENASSIST(&self, _0: AESKEYGENASSIST) {}
    fn visit_LFENCE(&self, _0: LFENCE) {}
    fn visit_BSF(&self, _0: BSF) {}
    fn visit_VDPPS(&self, _0: VDPPS) {}
    fn visit_VPSIGNB(&self, _0: VPSIGNB) {}
    fn visit_CLUI(&self, _0: CLUI) {}
    fn visit_MOVHPS(&self, _0: MOVHPS) {}
    fn visit_VFMSUBADD213PS(&self, _0: VFMSUBADD213PS) {}
    fn visit_RSQRTPS(&self, _0: RSQRTPS) {}
    fn visit_VSUBPD(&self, _0: VSUBPD) {}
    fn visit_PCMPESTRI(&self, _0: PCMPESTRI) {}
    fn visit_VEXTRACTF64X2(&self, _0: VEXTRACTF64X2) {}
    fn visit_VPSHRDVD(&self, _0: VPSHRDVD) {}
    fn visit_PADDQ(&self, _0: PADDQ) {}
    fn visit_POPA(&self, _0: POPA) {}
    fn visit_JNB(&self, _0: JNB) {}
    fn visit_RDPID(&self, _0: RDPID) {}
    fn visit_PINSRB(&self, _0: PINSRB) {}
    fn visit_VMFUNC(&self, _0: VMFUNC) {}
    fn visit_KANDQ(&self, _0: KANDQ) {}
    fn visit_SCASB(&self, _0: SCASB) {}
    fn visit_VPUNPCKHBW(&self, _0: VPUNPCKHBW) {}
    fn visit_PABSW(&self, _0: PABSW) {}
    fn visit_BSWAP(&self, _0: BSWAP) {}
    fn visit_FCOMP(&self, _0: FCOMP) {}
    fn visit_AESDECWIDE128KL(&self, _0: AESDECWIDE128KL) {}
    fn visit_LWPINS(&self, _0: LWPINS) {}
    fn visit_KSHIFTLW(&self, _0: KSHIFTLW) {}
    fn visit_VPDPBUSDS(&self, _0: VPDPBUSDS) {}
    fn visit_VEXTRACTI32X8(&self, _0: VEXTRACTI32X8) {}
    fn visit_VPMOVQ2M(&self, _0: VPMOVQ2M) {}
    fn visit_PCMPGTQ(&self, _0: PCMPGTQ) {}
    fn visit_VPBROADCASTMB2Q(&self, _0: VPBROADCASTMB2Q) {}
    fn visit_VPAND(&self, _0: VPAND) {}
    fn visit_VPSRLVQ(&self, _0: VPSRLVQ) {}
    fn visit_VPORQ(&self, _0: VPORQ) {}
    fn visit_FNSTENV(&self, _0: FNSTENV) {}
    fn visit_VPHADDSW(&self, _0: VPHADDSW) {}
    fn visit_VPSADBW(&self, _0: VPSADBW) {}
    fn visit_VFNMSUB231PD(&self, _0: VFNMSUB231PD) {}
    fn visit_VINSERTF64X2(&self, _0: VINSERTF64X2) {}
    fn visit_VEXTRACTF128(&self, _0: VEXTRACTF128) {}
    fn visit_VSCATTERPF1DPS(&self, _0: VSCATTERPF1DPS) {}
    fn visit_VPBLENDMD(&self, _0: VPBLENDMD) {}
    fn visit_SENDUIPI(&self, _0: SENDUIPI) {}
    fn visit_VMOVAPD(&self, _0: VMOVAPD) {}
    fn visit_VPMACSSWW(&self, _0: VPMACSSWW) {}
    fn visit_FLD(&self, _0: FLD) {}
    fn visit_VPMOVQW(&self, _0: VPMOVQW) {}
    fn visit_MAXPD(&self, _0: MAXPD) {}
    fn visit_VMULSD(&self, _0: VMULSD) {}
    fn visit_FXCH(&self, _0: FXCH) {}
    fn visit_VZEROUPPER(&self, _0: VZEROUPPER) {}
    fn visit_VPSHLDQ(&self, _0: VPSHLDQ) {}
    fn visit_MAXPS(&self, _0: MAXPS) {}
    fn visit_DPPD(&self, _0: DPPD) {}
    fn visit_PUNPCKHBW(&self, _0: PUNPCKHBW) {}
    fn visit_DIVPS(&self, _0: DIVPS) {}
    fn visit_RSTORSSP(&self, _0: RSTORSSP) {}
    fn visit_KANDNQ(&self, _0: KANDNQ) {}
    fn visit_VFIXUPIMMPD(&self, _0: VFIXUPIMMPD) {}
    fn visit_VPCOMPRESSW(&self, _0: VPCOMPRESSW) {}
    fn visit_VPERMT2Q(&self, _0: VPERMT2Q) {}
    fn visit_PCMPGTB(&self, _0: PCMPGTB) {}
    fn visit_FNCLEX(&self, _0: FNCLEX) {}
    fn visit_JNLE(&self, _0: JNLE) {}
    fn visit_VDIVSD(&self, _0: VDIVSD) {}
    fn visit_VPADDUSW(&self, _0: VPADDUSW) {}
    fn visit_CWD(&self, _0: CWD) {}
    fn visit_JNBE(&self, _0: JNBE) {}
    fn visit_PFRCPIT1(&self, _0: PFRCPIT1) {}
    fn visit_MOVNTDQ(&self, _0: MOVNTDQ) {}
    fn visit_VMPSADBW(&self, _0: VMPSADBW) {}
    fn visit_VFMADD231PS(&self, _0: VFMADD231PS) {}
    fn visit_VALIGNQ(&self, _0: VALIGNQ) {}
    fn visit_JBE(&self, _0: JBE) {}
    fn visit_MOVDQ2Q(&self, _0: MOVDQ2Q) {}
    fn visit_PCMPGTD(&self, _0: PCMPGTD) {}
    fn visit_MINPS(&self, _0: MINPS) {}
    fn visit_PMADDUBSW(&self, _0: PMADDUBSW) {}
    fn visit_VPSLLQ(&self, _0: VPSLLQ) {}
    fn visit_VPCMPEQW(&self, _0: VPCMPEQW) {}
    fn visit_VPXORQ(&self, _0: VPXORQ) {}
    fn visit_VEXTRACTI64X2(&self, _0: VEXTRACTI64X2) {}
    fn visit_INC(&self, _0: INC) {}
    fn visit_LEAVE(&self, _0: LEAVE) {}
    fn visit_VPCOMUB(&self, _0: VPCOMUB) {}
    fn visit_VMULPD(&self, _0: VMULPD) {}
    fn visit_VMOVSLDUP(&self, _0: VMOVSLDUP) {}
    fn visit_VPABSD(&self, _0: VPABSD) {}
    fn visit_VFMSUB213SS(&self, _0: VFMSUB213SS) {}
    fn visit_PFMAX(&self, _0: PFMAX) {}
    fn visit_KORTESTW(&self, _0: KORTESTW) {}
    fn visit_F2XM1(&self, _0: F2XM1) {}
    fn visit_LGDT(&self, _0: LGDT) {}
    fn visit_FFREE(&self, _0: FFREE) {}
    fn visit_PFRCP(&self, _0: PFRCP) {}
    fn visit_MOVQ2DQ(&self, _0: MOVQ2DQ) {}
    fn visit_CVTSI2SD(&self, _0: CVTSI2SD) {}
    fn visit_VP4DPWSSDS(&self, _0: VP4DPWSSDS) {}
    fn visit_VPMULTISHIFTQB(&self, _0: VPMULTISHIFTQB) {}
    fn visit_SHA256MSG1(&self, _0: SHA256MSG1) {}
    fn visit_PALIGNR(&self, _0: PALIGNR) {}
    fn visit_SYSENTER(&self, _0: SYSENTER) {}
    fn visit_VFMADD213PS(&self, _0: VFMADD213PS) {}
    fn visit_LOOPNE(&self, _0: LOOPNE) {}
    fn visit_PSLLDQ(&self, _0: PSLLDQ) {}
    fn visit_KANDB(&self, _0: KANDB) {}
    fn visit_VFMSUB231SD(&self, _0: VFMSUB231SD) {}
    fn visit_PADDD(&self, _0: PADDD) {}
    fn visit_ARPL(&self, _0: ARPL) {}
    fn visit_PMULUDQ(&self, _0: PMULUDQ) {}
    fn visit_VRCP28SD(&self, _0: VRCP28SD) {}
    fn visit_PSRLD(&self, _0: PSRLD) {}
    fn visit_BEXTR(&self, _0: BEXTR) {}
    fn visit_VSCATTERPF0QPD(&self, _0: VSCATTERPF0QPD) {}
    fn visit_VPSHRDVW(&self, _0: VPSHRDVW) {}
    fn visit_VMULPS(&self, _0: VMULPS) {}
    fn visit_CMPSD(&self, _0: CMPSD) {}
    fn visit_VFMADDSUB132PD(&self, _0: VFMADDSUB132PD) {}
    fn visit_UNPCKHPS(&self, _0: UNPCKHPS) {}
    fn visit_ADDSS(&self, _0: ADDSS) {}
    fn visit_VCVTSI2SS(&self, _0: VCVTSI2SS) {}
    fn visit_VFMSUB231SS(&self, _0: VFMSUB231SS) {}
    fn visit_IN(&self, _0: IN) {}
    fn visit_FBSTP(&self, _0: FBSTP) {}
    fn visit_SQRTPS(&self, _0: SQRTPS) {}
    fn visit_ENCODEKEY256(&self, _0: ENCODEKEY256) {}
    fn visit_VPMADDUBSW(&self, _0: VPMADDUBSW) {}
    fn visit_VFMADDSUB231PS(&self, _0: VFMADDSUB231PS) {}
    fn visit_VPBROADCASTQ(&self, _0: VPBROADCASTQ) {}
    fn visit_CMOVNO(&self, _0: CMOVNO) {}
    fn visit_ENQCMD(&self, _0: ENQCMD) {}
    fn visit_FLDCW(&self, _0: FLDCW) {}
    fn visit_FUCOMP(&self, _0: FUCOMP) {}
    fn visit_VMOVUPD(&self, _0: VMOVUPD) {}
    fn visit_PMAXSB(&self, _0: PMAXSB) {}
    fn visit_MULPD(&self, _0: MULPD) {}
    fn visit_CMPSB(&self, _0: CMPSB) {}
    fn visit_PSRLW(&self, _0: PSRLW) {}
    fn visit_LODSW(&self, _0: LODSW) {}
    fn visit_KORTESTD(&self, _0: KORTESTD) {}
    fn visit_VAESDEC(&self, _0: VAESDEC) {}
    fn visit_KORB(&self, _0: KORB) {}
    fn visit_JZ(&self, _0: JZ) {}
    fn visit_INVLPGB(&self, _0: INVLPGB) {}
    fn visit_VMOVDQU32(&self, _0: VMOVDQU32) {}
    fn visit_KMOVW(&self, _0: KMOVW) {}
    fn visit_CMPXCHG16B(&self, _0: CMPXCHG16B) {}
    fn visit_AESDEC256KL(&self, _0: AESDEC256KL) {}
    fn visit_VFNMSUBPD(&self, _0: VFNMSUBPD) {}
    fn visit_LOOP(&self, _0: LOOP) {}
    fn visit_SARX(&self, _0: SARX) {}
    fn visit_ENCLS(&self, _0: ENCLS) {}
    fn visit_MOVLHPS(&self, _0: MOVLHPS) {}
    fn visit_LODSD(&self, _0: LODSD) {}
    fn visit_CVTPD2DQ(&self, _0: CVTPD2DQ) {}
    fn visit_MOVSLDUP(&self, _0: MOVSLDUP) {}
    fn visit_PMOVZXWQ(&self, _0: PMOVZXWQ) {}
    fn visit_TZCNT(&self, _0: TZCNT) {}
    fn visit_AESENC256KL(&self, _0: AESENC256KL) {}
    fn visit_VFNMADD132PS(&self, _0: VFNMADD132PS) {}
    fn visit_TILERELEASE(&self, _0: TILERELEASE) {}
    fn visit_VRCP14SD(&self, _0: VRCP14SD) {}
    fn visit_VFPCLASSSS(&self, _0: VFPCLASSSS) {}
    fn visit_FISUBR(&self, _0: FISUBR) {}
    fn visit_FENI8087_NOP(&self, _0: FENI8087_NOP) {}
    fn visit_KNOTW(&self, _0: KNOTW) {}
    fn visit_VPCLMULQDQ(&self, _0: VPCLMULQDQ) {}
    fn visit_VPADDSW(&self, _0: VPADDSW) {}
    fn visit_XCRYPTCFB(&self, _0: XCRYPTCFB) {}
    fn visit_BLSI(&self, _0: BLSI) {}
    fn visit_VAESENCLAST(&self, _0: VAESENCLAST) {}
    fn visit_VPHSUBD(&self, _0: VPHSUBD) {}
    fn visit_VPMOVSXDQ(&self, _0: VPMOVSXDQ) {}
    fn visit_BNDMK(&self, _0: BNDMK) {}
    fn visit_BLENDVPD(&self, _0: BLENDVPD) {}
    fn visit_MULX(&self, _0: MULX) {}
    fn visit_VPOPCNTD(&self, _0: VPOPCNTD) {}
    fn visit_VPLZCNTQ(&self, _0: VPLZCNTQ) {}
    fn visit_CMOVNL(&self, _0: CMOVNL) {}
    fn visit_PFACC(&self, _0: PFACC) {}
    fn visit_VGATHERPF0QPD(&self, _0: VGATHERPF0QPD) {}
    fn visit_PF2IW(&self, _0: PF2IW) {}
    fn visit_NEG(&self, _0: NEG) {}
    fn visit_RDSSPD(&self, _0: RDSSPD) {}
    fn visit_LOOPE(&self, _0: LOOPE) {}
    fn visit_PDEP(&self, _0: PDEP) {}
    fn visit_SEAMRET(&self, _0: SEAMRET) {}
    fn visit_VALIGND(&self, _0: VALIGND) {}
    fn visit_VINSERTI32X4(&self, _0: VINSERTI32X4) {}
    fn visit_VSCATTERDPD(&self, _0: VSCATTERDPD) {}
    fn visit_VPSHLDD(&self, _0: VPSHLDD) {}
    fn visit_CMOVB(&self, _0: CMOVB) {}
    fn visit_STI(&self, _0: STI) {}
    fn visit_CVTDQ2PS(&self, _0: CVTDQ2PS) {}
    fn visit_PFMUL(&self, _0: PFMUL) {}
    fn visit_PSWAPD(&self, _0: PSWAPD) {}
    fn visit_TLBSYNC(&self, _0: TLBSYNC) {}
    fn visit_VROUNDSS(&self, _0: VROUNDSS) {}
    fn visit_VPEXTRQ(&self, _0: VPEXTRQ) {}
    fn visit_PEXTRD(&self, _0: PEXTRD) {}
    fn visit_VCMPPS(&self, _0: VCMPPS) {}
    fn visit_VRCP14SS(&self, _0: VRCP14SS) {}
    fn visit_VBROADCASTI32X2(&self, _0: VBROADCASTI32X2) {}
    fn visit_VINSERTI32X8(&self, _0: VINSERTI32X8) {}
    fn visit_VMPTRST(&self, _0: VMPTRST) {}
    fn visit_PBLENDVB(&self, _0: PBLENDVB) {}
    fn visit_PSLLW(&self, _0: PSLLW) {}
    fn visit_PCMPGTW(&self, _0: PCMPGTW) {}
    fn visit_SHA1MSG2(&self, _0: SHA1MSG2) {}
    fn visit_VFMADDSUB231PD(&self, _0: VFMADDSUB231PD) {}
    fn visit_VBLENDPS(&self, _0: VBLENDPS) {}
    fn visit_VFNMADD132PD(&self, _0: VFNMADD132PD) {}
    fn visit_VFMADDSUBPS(&self, _0: VFMADDSUBPS) {}
    fn visit_VPOR(&self, _0: VPOR) {}
    fn visit_VPERM2I128(&self, _0: VPERM2I128) {}
    fn visit_KXORQ(&self, _0: KXORQ) {}
    fn visit_VFRCZSS(&self, _0: VFRCZSS) {}
    fn visit_SYSRET(&self, _0: SYSRET) {}
    fn visit_IDIV(&self, _0: IDIV) {}
    fn visit_STC(&self, _0: STC) {}
    fn visit_EMMS(&self, _0: EMMS) {}
    fn visit_VGATHERPF0DPD(&self, _0: VGATHERPF0DPD) {}
    fn visit_MOVNTQ(&self, _0: MOVNTQ) {}
    fn visit_CVTTPD2PI(&self, _0: CVTTPD2PI) {}
    fn visit_SAR(&self, _0: SAR) {}
    fn visit_DIVSD(&self, _0: DIVSD) {}
    fn visit_VMASKMOVPS(&self, _0: VMASKMOVPS) {}
    fn visit_VPMOVSXBQ(&self, _0: VPMOVSXBQ) {}
    fn visit_GETSEC(&self, _0: GETSEC) {}
    fn visit_KXNORW(&self, _0: KXNORW) {}
    fn visit_PREFETCH_EXCLUSIVE(&self, _0: PREFETCH_EXCLUSIVE) {}
    fn visit_INT(&self, _0: INT) {}
    fn visit_VPMULHRSW(&self, _0: VPMULHRSW) {}
    fn visit_SCASQ(&self, _0: SCASQ) {}
    fn visit_CVTTSD2SI(&self, _0: CVTTSD2SI) {}
    fn visit_PREFETCH_RESERVED(&self, _0: PREFETCH_RESERVED) {}
    fn visit_XSAVES64(&self, _0: XSAVES64) {}
    fn visit_VFMSUB132SD(&self, _0: VFMSUB132SD) {}
    fn visit_VFMSUB213PD(&self, _0: VFMSUB213PD) {}
    fn visit_VPMOVZXWQ(&self, _0: VPMOVZXWQ) {}
    fn visit_MOVHPD(&self, _0: MOVHPD) {}
    fn visit_CMOVNZ(&self, _0: CMOVNZ) {}
    fn visit_XSAVEC64(&self, _0: XSAVEC64) {}
    fn visit_VPADDSB(&self, _0: VPADDSB) {}
    fn visit_ENCODEKEY128(&self, _0: ENCODEKEY128) {}
    fn visit_IRET(&self, _0: IRET) {}
    fn visit_MONTMUL(&self, _0: MONTMUL) {}
    fn visit_VPUNPCKHQDQ(&self, _0: VPUNPCKHQDQ) {}
    fn visit_VPEXTRB(&self, _0: VPEXTRB) {}
    fn visit_SQRTSS(&self, _0: SQRTSS) {}
    fn visit_KXORW(&self, _0: KXORW) {}
    fn visit_SUBPD(&self, _0: SUBPD) {}
    fn visit_VPSHAQ(&self, _0: VPSHAQ) {}
    fn visit_FUCOMIP(&self, _0: FUCOMIP) {}
    fn visit_AESDECLAST(&self, _0: AESDECLAST) {}
    fn visit_VPMOVUSQD(&self, _0: VPMOVUSQD) {}
    fn visit_INVLPGA(&self, _0: INVLPGA) {}
    fn visit_FCMOVNB(&self, _0: FCMOVNB) {}
    fn visit_VFMSUB132PD(&self, _0: VFMSUB132PD) {}
    fn visit_INT1(&self, _0: INT1) {}
    fn visit_XGETBV(&self, _0: XGETBV) {}
    fn visit_FEMMS(&self, _0: FEMMS) {}
    fn visit_VCVTQQ2PD(&self, _0: VCVTQQ2PD) {}
    fn visit_VCVTPS2PH(&self, _0: VCVTPS2PH) {}
    fn visit_CVTSS2SD(&self, _0: CVTSS2SD) {}
    fn visit_PSUBB(&self, _0: PSUBB) {}
    fn visit_MOVNTI(&self, _0: MOVNTI) {}
    fn visit_VMRUN(&self, _0: VMRUN) {}
    fn visit_FPTAN(&self, _0: FPTAN) {}
    fn visit_MOVNTSD(&self, _0: MOVNTSD) {}
    fn visit_XEND(&self, _0: XEND) {}
    fn visit_LOADIWKEY(&self, _0: LOADIWKEY) {}
    fn visit_VSHUFPS(&self, _0: VSHUFPS) {}
    fn visit_VPMOVZXBW(&self, _0: VPMOVZXBW) {}
    fn visit_SETO(&self, _0: SETO) {}
    fn visit_TDPBUUD(&self, _0: TDPBUUD) {}
    fn visit_VRSQRT28PS(&self, _0: VRSQRT28PS) {}
    fn visit_VPERMI2D(&self, _0: VPERMI2D) {}
    fn visit_OUTSB(&self, _0: OUTSB) {}
    fn visit_RDSSPQ(&self, _0: RDSSPQ) {}
    fn visit_VPAVGB(&self, _0: VPAVGB) {}
    fn visit_POPFQ(&self, _0: POPFQ) {}
    fn visit_AAA(&self, _0: AAA) {}
    fn visit_LGS(&self, _0: LGS) {}
    fn visit_PSLLD(&self, _0: PSLLD) {}
    fn visit_VPSHLW(&self, _0: VPSHLW) {}
    fn visit_VRNDSCALEPD(&self, _0: VRNDSCALEPD) {}
    fn visit_VRNDSCALESS(&self, _0: VRNDSCALESS) {}
    fn visit_SHR(&self, _0: SHR) {}
    fn visit_PSADBW(&self, _0: PSADBW) {}
    fn visit_SETL(&self, _0: SETL) {}
    fn visit_VPINSRB(&self, _0: VPINSRB) {}
    fn visit_SETLE(&self, _0: SETLE) {}
    fn visit_VFMADD213SD(&self, _0: VFMADD213SD) {}
    fn visit_VFMADDSUB213PS(&self, _0: VFMADDSUB213PS) {}
    fn visit_KORTESTB(&self, _0: KORTESTB) {}
    fn visit_VGATHERPF1QPD(&self, _0: VGATHERPF1QPD) {}
    fn visit_VINSERTI64X4(&self, _0: VINSERTI64X4) {}
    fn visit_VMOVDQU64(&self, _0: VMOVDQU64) {}
    fn visit_VPSHLDVD(&self, _0: VPSHLDVD) {}
    fn visit_PACKSSDW(&self, _0: PACKSSDW) {}
    fn visit_XSUSLDTRK(&self, _0: XSUSLDTRK) {}
    fn visit_FCMOVNU(&self, _0: FCMOVNU) {}
    fn visit_VMOVLHPS(&self, _0: VMOVLHPS) {}
    fn visit_VPCMPQ(&self, _0: VPCMPQ) {}
    fn visit_VPRORD(&self, _0: VPRORD) {}
    fn visit_VPERMIL2PD(&self, _0: VPERMIL2PD) {}
    fn visit_TILELOADDT1(&self, _0: TILELOADDT1) {}
    fn visit_FSUBRP(&self, _0: FSUBRP) {}
    fn visit_MWAIT(&self, _0: MWAIT) {}
    fn visit_BLCFILL(&self, _0: BLCFILL) {}
    fn visit_BZHI(&self, _0: BZHI) {}
    fn visit_WBINVD(&self, _0: WBINVD) {}
    fn visit_BTC(&self, _0: BTC) {}
    fn visit_XRSTOR64(&self, _0: XRSTOR64) {}
    fn visit_VRCPPS(&self, _0: VRCPPS) {}
    fn visit_PAVGB(&self, _0: PAVGB) {}
    fn visit_PHADDD(&self, _0: PHADDD) {}
    fn visit_VPHSUBW(&self, _0: VPHSUBW) {}
    fn visit_CLRSSBSY(&self, _0: CLRSSBSY) {}
    fn visit_SETNS(&self, _0: SETNS) {}
    fn visit_VEXTRACTI64X4(&self, _0: VEXTRACTI64X4) {}
    fn visit_VMOVLPS(&self, _0: VMOVLPS) {}
    fn visit_ADOX(&self, _0: ADOX) {}
    fn visit_ANDPD(&self, _0: ANDPD) {}
    fn visit_VADDSD(&self, _0: VADDSD) {}
    fn visit_VCMPSS(&self, _0: VCMPSS) {}
    fn visit_PXOR(&self, _0: PXOR) {}
    fn visit_VMOVNTPS(&self, _0: VMOVNTPS) {}
    fn visit_VFMADD213SS(&self, _0: VFMADD213SS) {}
    fn visit_VPMULDQ(&self, _0: VPMULDQ) {}
    fn visit_CMOVNP(&self, _0: CMOVNP) {}
    fn visit_CLFLUSHOPT(&self, _0: CLFLUSHOPT) {}
    fn visit_VFNMSUB231PS(&self, _0: VFNMSUB231PS) {}
    fn visit_KNOTQ(&self, _0: KNOTQ) {}
    fn visit_VCVTTSS2USI(&self, _0: VCVTTSS2USI) {}
    fn visit_VUCOMISD(&self, _0: VUCOMISD) {}
    fn visit_VGETEXPPD(&self, _0: VGETEXPPD) {}
    fn visit_HLT(&self, _0: HLT) {}
    fn visit_VPMAXUQ(&self, _0: VPMAXUQ) {}
    fn visit_SEAMOPS(&self, _0: SEAMOPS) {}
    fn visit_VPMINUQ(&self, _0: VPMINUQ) {}
    fn visit_KXNORD(&self, _0: KXNORD) {}
    fn visit_VSHUFF32X4(&self, _0: VSHUFF32X4) {}
    fn visit_VPBLENDMB(&self, _0: VPBLENDMB) {}
    fn visit_HADDPD(&self, _0: HADDPD) {}
    fn visit_VPMOVQB(&self, _0: VPMOVQB) {}
    fn visit_HADDPS(&self, _0: HADDPS) {}
    fn visit_FTST(&self, _0: FTST) {}
    fn visit_BLSR(&self, _0: BLSR) {}
    fn visit_PFRSQIT1(&self, _0: PFRSQIT1) {}
    fn visit_VEXTRACTF64X4(&self, _0: VEXTRACTF64X4) {}
    fn visit_XBEGIN(&self, _0: XBEGIN) {}
    fn visit_VFNMADD213PD(&self, _0: VFNMADD213PD) {}
    fn visit_PMULLW(&self, _0: PMULLW) {}
    fn visit_ENDBR64(&self, _0: ENDBR64) {}
    fn visit_MOVSW(&self, _0: MOVSW) {}
    fn visit_PABSD(&self, _0: PABSD) {}
    fn visit_PHMINPOSUW(&self, _0: PHMINPOSUW) {}
    fn visit_PMULDQ(&self, _0: PMULDQ) {}
    fn visit_MONITORX(&self, _0: MONITORX) {}
    fn visit_RMPADJUST(&self, _0: RMPADJUST) {}
    fn visit_VCOMPRESSPD(&self, _0: VCOMPRESSPD) {}
    fn visit_VCVTTPS2UDQ(&self, _0: VCVTTPS2UDQ) {}
    fn visit_VROUNDSD(&self, _0: VROUNDSD) {}
    fn visit_MOVUPS(&self, _0: MOVUPS) {}
    fn visit_VPERMT2W(&self, _0: VPERMT2W) {}
    fn visit_SUBSD(&self, _0: SUBSD) {}
    fn visit_MOVSXD(&self, _0: MOVSXD) {}
    fn visit_VPERMI2Q(&self, _0: VPERMI2Q) {}
    fn visit_ROUNDSS(&self, _0: ROUNDSS) {}
    fn visit_VHADDPD(&self, _0: VHADDPD) {}
    fn visit_VPXORD(&self, _0: VPXORD) {}
    fn visit_PUNPCKHWD(&self, _0: PUNPCKHWD) {}
    fn visit_KSHIFTLD(&self, _0: KSHIFTLD) {}
    fn visit_INSW(&self, _0: INSW) {}
    fn visit_CVTSI2SS(&self, _0: CVTSI2SS) {}
    fn visit_VGATHERPF0QPS(&self, _0: VGATHERPF0QPS) {}
    fn visit_VSQRTSS(&self, _0: VSQRTSS) {}
    fn visit_VPMINSW(&self, _0: VPMINSW) {}
    fn visit_VSUBPS(&self, _0: VSUBPS) {}
    fn visit_FUCOM(&self, _0: FUCOM) {}
    fn visit_VPSLLW(&self, _0: VPSLLW) {}
    fn visit_PFSUBR(&self, _0: PFSUBR) {}
    fn visit_SETSSBSY(&self, _0: SETSSBSY) {}
    fn visit_PSUBUSW(&self, _0: PSUBUSW) {}
    fn visit_FXSAVE64(&self, _0: FXSAVE64) {}
    fn visit_LWPVAL(&self, _0: LWPVAL) {}
    fn visit_VMOVUPS(&self, _0: VMOVUPS) {}
    fn visit_VPEXTRW(&self, _0: VPEXTRW) {}
    fn visit_VINSERTF64X4(&self, _0: VINSERTF64X4) {}
    fn visit_VPOPCNTQ(&self, _0: VPOPCNTQ) {}
    fn visit_FDISI8087_NOP(&self, _0: FDISI8087_NOP) {}
    fn visit_ROR(&self, _0: ROR) {}
    fn visit_VPMOVDB(&self, _0: VPMOVDB) {}
    fn visit_XCRYPTOFB(&self, _0: XCRYPTOFB) {}
    fn visit_BNDCL(&self, _0: BNDCL) {}
    fn visit_VPSCATTERQD(&self, _0: VPSCATTERQD) {}
    fn visit_AAS(&self, _0: AAS) {}
    fn visit_SYSCALL(&self, _0: SYSCALL) {}
    fn visit_VRNDSCALESD(&self, _0: VRNDSCALESD) {}
    fn visit_VFNMSUB213PD(&self, _0: VFNMSUB213PD) {}
    fn visit_VRSQRT28PD(&self, _0: VRSQRT28PD) {}
    fn visit_VCMPPD(&self, _0: VCMPPD) {}
    fn visit_FPREM(&self, _0: FPREM) {}
    fn visit_MOVLPD(&self, _0: MOVLPD) {}
    fn visit_XRSTOR(&self, _0: XRSTOR) {}
    fn visit_GF2P8AFFINEQB(&self, _0: GF2P8AFFINEQB) {}
    fn visit_AESENCWIDE256KL(&self, _0: AESENCWIDE256KL) {}
    fn visit_CMOVNB(&self, _0: CMOVNB) {}
    fn visit_ENQCMDS(&self, _0: ENQCMDS) {}
    fn visit_FLDLG2(&self, _0: FLDLG2) {}
    fn visit_PUNPCKHDQ(&self, _0: PUNPCKHDQ) {}
    fn visit_PADDUSW(&self, _0: PADDUSW) {}
    fn visit_VFNMADDPS(&self, _0: VFNMADDPS) {}
    fn visit_FYL2XP1(&self, _0: FYL2XP1) {}
    fn visit_VPSLLVD(&self, _0: VPSLLVD) {}
    fn visit_PADDSW(&self, _0: PADDSW) {}
    fn visit_VMOVD(&self, _0: VMOVD) {}
    fn visit_VPACKSSDW(&self, _0: VPACKSSDW) {}
    fn visit_PREFETCHT1(&self, _0: PREFETCHT1) {}
    fn visit_VEXPANDPS(&self, _0: VEXPANDPS) {}
    fn visit_VPANDD(&self, _0: VPANDD) {}
    fn visit_VPCONFLICTQ(&self, _0: VPCONFLICTQ) {}
    fn visit_VPSLLVW(&self, _0: VPSLLVW) {}
    fn visit_VPEXPANDW(&self, _0: VPEXPANDW) {}
    fn visit_PFRCPIT2(&self, _0: PFRCPIT2) {}
    fn visit_VPMOVM2Q(&self, _0: VPMOVM2Q) {}
    fn visit_FNINIT(&self, _0: FNINIT) {}
    fn visit_VCVTNE2PS2BF16(&self, _0: VCVTNE2PS2BF16) {}
    fn visit_VPERMIL2PS(&self, _0: VPERMIL2PS) {}
    fn visit_XCHG(&self, _0: XCHG) {}
    fn visit_VPROTW(&self, _0: VPROTW) {}
    fn visit_VBLENDVPD(&self, _0: VBLENDVPD) {}
    fn visit_VPCOMW(&self, _0: VPCOMW) {}
    fn visit_VFNMADD231PS(&self, _0: VFNMADD231PS) {}
    fn visit_VMOVHLPS(&self, _0: VMOVHLPS) {}
    fn visit_VGATHERPF1DPD(&self, _0: VGATHERPF1DPD) {}
    fn visit_VPMOVSQW(&self, _0: VPMOVSQW) {}
    fn visit_PMAXUW(&self, _0: PMAXUW) {}
    fn visit_VPRORQ(&self, _0: VPRORQ) {}
    fn visit_BTS(&self, _0: BTS) {}
    fn visit_DIVSS(&self, _0: DIVSS) {}
    fn visit_VMXON(&self, _0: VMXON) {}
    fn visit_SHUFPS(&self, _0: SHUFPS) {}
    fn visit_FLDL2T(&self, _0: FLDL2T) {}
    fn visit_SMSW(&self, _0: SMSW) {}
    fn visit_INTO(&self, _0: INTO) {}
    fn visit_PADDW(&self, _0: PADDW) {}
    fn visit_POPF(&self, _0: POPF) {}
    fn visit_FXTRACT(&self, _0: FXTRACT) {}
    fn visit_VPMINSQ(&self, _0: VPMINSQ) {}
    fn visit_PAND(&self, _0: PAND) {}
    fn visit_INT3(&self, _0: INT3) {}
    fn visit_XRSTORS(&self, _0: XRSTORS) {}
    fn visit_VPSIGNW(&self, _0: VPSIGNW) {}
    fn visit_CLDEMOTE(&self, _0: CLDEMOTE) {}
    fn visit_SUBPS(&self, _0: SUBPS) {}
    fn visit_IMUL(&self, _0: IMUL) {}
    fn visit_SHA256RNDS2(&self, _0: SHA256RNDS2) {}
    fn visit_PFADD(&self, _0: PFADD) {}
    fn visit_VPACKUSWB(&self, _0: VPACKUSWB) {}
    fn visit_VSTMXCSR(&self, _0: VSTMXCSR) {}
    fn visit_VUNPCKLPS(&self, _0: VUNPCKLPS) {}
    fn visit_PUSHF(&self, _0: PUSHF) {}
    fn visit_PSIGNB(&self, _0: PSIGNB) {}
    fn visit_BNDLDX(&self, _0: BNDLDX) {}
    fn visit_VPMOVSXWQ(&self, _0: VPMOVSXWQ) {}
    fn visit_JECXZ(&self, _0: JECXZ) {}
    fn visit_ANDN(&self, _0: ANDN) {}
    fn visit_KTESTD(&self, _0: KTESTD) {}
    fn visit_VHSUBPS(&self, _0: VHSUBPS) {}
    fn visit_VRSQRT14SD(&self, _0: VRSQRT14SD) {}
    fn visit_VPSRAVW(&self, _0: VPSRAVW) {}
    fn visit_VPSHLDW(&self, _0: VPSHLDW) {}
    fn visit_UD0(&self, _0: UD0) {}
    fn visit_CMPSQ(&self, _0: CMPSQ) {}
    fn visit_XCRYPTCTR(&self, _0: XCRYPTCTR) {}
    fn visit_VCVTDQ2PD(&self, _0: VCVTDQ2PD) {}
    fn visit_VPERMI2PS(&self, _0: VPERMI2PS) {}
    fn visit_FLDL2E(&self, _0: FLDL2E) {}
    fn visit_FDIV(&self, _0: FDIV) {}
    fn visit_ORPD(&self, _0: ORPD) {}
    fn visit_MOVAPD(&self, _0: MOVAPD) {}
    fn visit_POPFD(&self, _0: POPFD) {}
    fn visit_PCONFIG(&self, _0: PCONFIG) {}
    fn visit_VEXTRACTI128(&self, _0: VEXTRACTI128) {}
    fn visit_V4FMADDPS(&self, _0: V4FMADDPS) {}
    fn visit_VCVTSD2USI(&self, _0: VCVTSD2USI) {}
    fn visit_VPCMPUW(&self, _0: VPCMPUW) {}
    fn visit_VPSRLVW(&self, _0: VPSRLVW) {}
    fn visit_VRSQRT14SS(&self, _0: VRSQRT14SS) {}
    fn visit_FCMOVB(&self, _0: FCMOVB) {}
    fn visit_VPSHUFD(&self, _0: VPSHUFD) {}
    fn visit_RDPRU(&self, _0: RDPRU) {}
    fn visit_JS(&self, _0: JS) {}
    fn visit_VFNMADDSD(&self, _0: VFNMADDSD) {}
    fn visit_VPTESTNMD(&self, _0: VPTESTNMD) {}
    fn visit_VPOPCNTW(&self, _0: VPOPCNTW) {}
    fn visit_SETNLE(&self, _0: SETNLE) {}
    fn visit_STGI(&self, _0: STGI) {}
    fn visit_VPANDNQ(&self, _0: VPANDNQ) {}
    fn visit_BOUND(&self, _0: BOUND) {}
    fn visit_XABORT(&self, _0: XABORT) {}
    fn visit_VCVTTSD2SI(&self, _0: VCVTTSD2SI) {}
    fn visit_RDMSR(&self, _0: RDMSR) {}
    fn visit_VFMSUB231PD(&self, _0: VFMSUB231PD) {}
    fn visit_VINSERTF32X4(&self, _0: VINSERTF32X4) {}
    fn visit_VPTERNLOGQ(&self, _0: VPTERNLOGQ) {}
    fn visit_AESIMC(&self, _0: AESIMC) {}
    fn visit_VFNMSUB213SS(&self, _0: VFNMSUB213SS) {}
    fn visit_KNOTD(&self, _0: KNOTD) {}
    fn visit_VSQRTSD(&self, _0: VSQRTSD) {}
    fn visit_VCVTTPD2UDQ(&self, _0: VCVTTPD2UDQ) {}
    fn visit_PCMPISTRM(&self, _0: PCMPISTRM) {}
    fn visit_FRNDINT(&self, _0: FRNDINT) {}
    fn visit_VSUBSD(&self, _0: VSUBSD) {}
    fn visit_FIADD(&self, _0: FIADD) {}
    fn visit_TDPBSSD(&self, _0: TDPBSSD) {}
    fn visit_VINSERTI64X2(&self, _0: VINSERTI64X2) {}
    fn visit_PADDUSB(&self, _0: PADDUSB) {}
    fn visit_VPSUBUSB(&self, _0: VPSUBUSB) {}
    fn visit_MULSD(&self, _0: MULSD) {}
    fn visit_VCVTPS2QQ(&self, _0: VCVTPS2QQ) {}
    fn visit_VPANDQ(&self, _0: VPANDQ) {}
    fn visit_VGETEXPSD(&self, _0: VGETEXPSD) {}
    fn visit_STR(&self, _0: STR) {}
    fn visit_PANDN(&self, _0: PANDN) {}
    fn visit_INSD(&self, _0: INSD) {}
    fn visit_AESDECWIDE256KL(&self, _0: AESDECWIDE256KL) {}
    fn visit_VPMAXSB(&self, _0: VPMAXSB) {}
    fn visit_VMRESUME(&self, _0: VMRESUME) {}
    fn visit_VCVTQQ2PS(&self, _0: VCVTQQ2PS) {}
    fn visit_FNOP(&self, _0: FNOP) {}
    fn visit_DIV(&self, _0: DIV) {}
    fn visit_RDPKRU(&self, _0: RDPKRU) {}
    fn visit_SIDT(&self, _0: SIDT) {}
    fn visit_FLD1(&self, _0: FLD1) {}
    fn visit_FIMUL(&self, _0: FIMUL) {}
    fn visit_RET(&self, _0: RET) {}
    fn visit_ANDNPS(&self, _0: ANDNPS) {}
    fn visit_VPHADDWD(&self, _0: VPHADDWD) {}
    fn visit_PHSUBSW(&self, _0: PHSUBSW) {}
    fn visit_PSHUFLW(&self, _0: PSHUFLW) {}
    fn visit_VPMOVZXBQ(&self, _0: VPMOVZXBQ) {}
    fn visit_VFNMADD213SS(&self, _0: VFNMADD213SS) {}
    fn visit_VPERMQ(&self, _0: VPERMQ) {}
    fn visit_KADDW(&self, _0: KADDW) {}
    fn visit_VGETMANTSD(&self, _0: VGETMANTSD) {}
    fn visit_FSUBR(&self, _0: FSUBR) {}
    fn visit_KANDW(&self, _0: KANDW) {}
    fn visit_FXSAVE(&self, _0: FXSAVE) {}
    fn visit_VPSIGND(&self, _0: VPSIGND) {}
    fn visit_PSRAW(&self, _0: PSRAW) {}
    fn visit_KTESTB(&self, _0: KTESTB) {}
    fn visit_VPANDND(&self, _0: VPANDND) {}
    fn visit_FADDP(&self, _0: FADDP) {}
    fn visit_VPERMI2PD(&self, _0: VPERMI2PD) {}
    fn visit_PMULHW(&self, _0: PMULHW) {}
    fn visit_PSUBUSB(&self, _0: PSUBUSB) {}
    fn visit_VRCP14PS(&self, _0: VRCP14PS) {}
    fn visit_SHUFPD(&self, _0: SHUFPD) {}
    fn visit_FCMOVU(&self, _0: FCMOVU) {}
    fn visit_STOSD(&self, _0: STOSD) {}
    fn visit_CVTPS2DQ(&self, _0: CVTPS2DQ) {}
    fn visit_VROUNDPD(&self, _0: VROUNDPD) {}
    fn visit_VPSHLDVW(&self, _0: VPSHLDVW) {}
    fn visit_PF2ID(&self, _0: PF2ID) {}
    fn visit_VP2INTERSECTD(&self, _0: VP2INTERSECTD) {}
    fn visit_VPHADDUWD(&self, _0: VPHADDUWD) {}
    fn visit_VPANDN(&self, _0: VPANDN) {}
    fn visit_FXRSTOR64(&self, _0: FXRSTOR64) {}
    fn visit_MFENCE(&self, _0: MFENCE) {}
    fn visit_VPORD(&self, _0: VPORD) {}
    fn visit_INVVPID(&self, _0: INVVPID) {}
    fn visit_VPROTB(&self, _0: VPROTB) {}
    fn visit_FRSTOR(&self, _0: FRSTOR) {}
    fn visit_VPERMD(&self, _0: VPERMD) {}
    fn visit_VFNMSUB132PD(&self, _0: VFNMSUB132PD) {}
    fn visit_KMOVQ(&self, _0: KMOVQ) {}
    fn visit_RDPMC(&self, _0: RDPMC) {}
    fn visit_SETNBE(&self, _0: SETNBE) {}
    fn visit_PADDSB(&self, _0: PADDSB) {}
    fn visit_VSQRTPS(&self, _0: VSQRTPS) {}
    fn visit_JNL(&self, _0: JNL) {}
    fn visit_VFMSUBSS(&self, _0: VFMSUBSS) {}
    fn visit_VPTESTNMQ(&self, _0: VPTESTNMQ) {}
    fn visit_VPHSUBBW(&self, _0: VPHSUBBW) {}
    fn visit_VPCMPUB(&self, _0: VPCMPUB) {}
    fn visit_XADD(&self, _0: XADD) {}
    fn visit_RMPUPDATE(&self, _0: RMPUPDATE) {}
    fn visit_VSHUFPD(&self, _0: VSHUFPD) {}
    fn visit_STTILECFG(&self, _0: STTILECFG) {}
    fn visit_VFMSUB231PS(&self, _0: VFMSUB231PS) {}
    fn visit_PADDB(&self, _0: PADDB) {}
    fn visit_VDBPSADBW(&self, _0: VDBPSADBW) {}
    fn visit_SETB(&self, _0: SETB) {}
    fn visit_VMOVDDUP(&self, _0: VMOVDDUP) {}
    fn visit_VPHMINPOSUW(&self, _0: VPHMINPOSUW) {}
    fn visit_FIST(&self, _0: FIST) {}
    fn visit_PEXTRQ(&self, _0: PEXTRQ) {}
    fn visit_VMLOAD(&self, _0: VMLOAD) {}
    fn visit_VMAXPD(&self, _0: VMAXPD) {}
    fn visit_VORPS(&self, _0: VORPS) {}
    fn visit_KMOVB(&self, _0: KMOVB) {}
    fn visit_VPERMI2W(&self, _0: VPERMI2W) {}
    fn visit_KSHIFTLB(&self, _0: KSHIFTLB) {}
    fn visit_MULSS(&self, _0: MULSS) {}
    fn visit_PFRSQRT(&self, _0: PFRSQRT) {}
    fn visit_FBLD(&self, _0: FBLD) {}
    fn visit_VCVTPD2UDQ(&self, _0: VCVTPD2UDQ) {}
    fn visit_OUTSW(&self, _0: OUTSW) {}
    fn visit_OUTSD(&self, _0: OUTSD) {}
    fn visit_VPHADDBW(&self, _0: VPHADDBW) {}
    fn visit_VFMSUBPD(&self, _0: VFMSUBPD) {}
    fn visit_SHA1RNDS4(&self, _0: SHA1RNDS4) {}
    fn visit_LIDT(&self, _0: LIDT) {}
    fn visit_CMPXCHG(&self, _0: CMPXCHG) {}
    fn visit_GF2P8MULB(&self, _0: GF2P8MULB) {}
    fn visit_VBROADCASTI64X4(&self, _0: VBROADCASTI64X4) {}
    fn visit_FLDLN2(&self, _0: FLDLN2) {}
    fn visit_VFMADDSS(&self, _0: VFMADDSS) {}
    fn visit_FMUL(&self, _0: FMUL) {}
    fn visit_VCMPSD(&self, _0: VCMPSD) {}
    fn visit_KUNPCKWD(&self, _0: KUNPCKWD) {}
    fn visit_VPCMPGTW(&self, _0: VPCMPGTW) {}
    fn visit_VBROADCASTI32X8(&self, _0: VBROADCASTI32X8) {}
    fn visit_VPSHLDVQ(&self, _0: VPSHLDVQ) {}
    fn visit_LAR(&self, _0: LAR) {}
    fn visit_UD1(&self, _0: UD1) {}
    fn visit_JMP(&self, _0: JMP) {}
    fn visit_VPCMPUQ(&self, _0: VPCMPUQ) {}
    fn visit_BLSFILL(&self, _0: BLSFILL) {}
    fn visit_VPCMPW(&self, _0: VPCMPW) {}
    fn visit_VPCOMQ(&self, _0: VPCOMQ) {}
    fn visit_PHADDW(&self, _0: PHADDW) {}
    fn visit_VFMADDSD(&self, _0: VFMADDSD) {}
    fn visit_FCOS(&self, _0: FCOS) {}
    fn visit_PMAXUD(&self, _0: PMAXUD) {}
}
