[package]
name = "llvm-ir-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-ir = { version = "0.9.0", features = ["llvm-15"] }
cpp_demangle = "0.4.3"
anyhow = "1"
