use xed_sys::{XED_REG_AH, XED_REG_AL, XED_REG_AX, XED_REG_BH, XED_REG_BL, XED_REG_BND0, XED_REG_BND1, XED_REG_BND2, XED_REG_BND3, XED_REG_BNDCFGU, XED_REG_BNDSTATUS, XED_REG_BP, XED_REG_BPL, XED_REG_BX, XED_REG_CH, XED_REG_CL, xed_reg_class_enum_t, XED_REG_CR0, XED_REG_CR1, XED_REG_CR10, XED_REG_CR11, XED_REG_CR12, XED_REG_CR13, XED_REG_CR14, XED_REG_CR15, XED_REG_CR2, XED_REG_CR3, XED_REG_CR4, XED_REG_CR5, XED_REG_CR6, XED_REG_CR7, XED_REG_CR8, XED_REG_CR9, XED_REG_CS, XED_REG_CX, XED_REG_DH, XED_REG_DI, XED_REG_DIL, XED_REG_DL, XED_REG_DR0, XED_REG_DR1, XED_REG_DR2, XED_REG_DR3, XED_REG_DR4, XED_REG_DR5, XED_REG_DR6, XED_REG_DR7, XED_REG_DS, XED_REG_DX, XED_REG_EAX, XED_REG_EBP, XED_REG_EBX, XED_REG_ECX, XED_REG_EDI, XED_REG_EDX, XED_REG_EFLAGS, XED_REG_EIP, XED_REG_ERROR, XED_REG_ES, XED_REG_ESI, XED_REG_ESP, XED_REG_FLAGS, XED_REG_FS, XED_REG_FSBASE, XED_REG_GDTR, XED_REG_GS, XED_REG_GSBASE, XED_REG_IA32_U_CET, XED_REG_IDTR, XED_REG_INVALID_FIRST, XED_REG_IP, XED_REG_K0, XED_REG_K1, XED_REG_K2, XED_REG_K3, XED_REG_K4, XED_REG_K5, XED_REG_K6, XED_REG_K7, XED_REG_LAST, XED_REG_LDTR, XED_REG_MMX0, XED_REG_MMX1, XED_REG_MMX2, XED_REG_MMX3, XED_REG_MMX4, XED_REG_MMX5, XED_REG_MMX6, XED_REG_MMX7, XED_REG_MSRS, XED_REG_MXCSR, XED_REG_R10, XED_REG_R10B, XED_REG_R10D, XED_REG_R10W, XED_REG_R11, XED_REG_R11B, XED_REG_R11D, XED_REG_R11W, XED_REG_R12, XED_REG_R12B, XED_REG_R12D, XED_REG_R12W, XED_REG_R13, XED_REG_R13B, XED_REG_R13D, XED_REG_R13W, XED_REG_R14, XED_REG_R14B, XED_REG_R14D, XED_REG_R14W, XED_REG_R15, XED_REG_R15B, XED_REG_R15D, XED_REG_R15W, XED_REG_R8, XED_REG_R8B, XED_REG_R8D, XED_REG_R8W, XED_REG_R9, XED_REG_R9B, XED_REG_R9D, XED_REG_R9W, XED_REG_RAX, XED_REG_RBP, XED_REG_RBX, XED_REG_RCX, XED_REG_RDI, XED_REG_RDX, XED_REG_RFLAGS, XED_REG_RIP, XED_REG_RSI, XED_REG_RSP, XED_REG_SI, XED_REG_SIL, XED_REG_SP, XED_REG_SPL, XED_REG_SS, XED_REG_SSP, XED_REG_ST0, XED_REG_ST1, XED_REG_ST2, XED_REG_ST3, XED_REG_ST4, XED_REG_ST5, XED_REG_ST6, XED_REG_ST7, XED_REG_STACKPOP, XED_REG_STACKPUSH, XED_REG_TILECONFIG, XED_REG_TMM0, XED_REG_TMM1, XED_REG_TMM2, XED_REG_TMM3, XED_REG_TMM4, XED_REG_TMM5, XED_REG_TMM6, XED_REG_TMM7, XED_REG_TMP0, XED_REG_TMP1, XED_REG_TMP10, XED_REG_TMP11, XED_REG_TMP12, XED_REG_TMP13, XED_REG_TMP14, XED_REG_TMP15, XED_REG_TMP2, XED_REG_TMP3, XED_REG_TMP4, XED_REG_TMP5, XED_REG_TMP6, XED_REG_TMP7, XED_REG_TMP8, XED_REG_TMP9, XED_REG_TR, XED_REG_TSC, XED_REG_TSCAUX, XED_REG_UIF, XED_REG_X87CONTROL, XED_REG_X87LASTCS, XED_REG_X87LASTDP, XED_REG_X87LASTDS, XED_REG_X87LASTIP, XED_REG_X87OPCODE, XED_REG_X87POP, XED_REG_X87POP2, XED_REG_X87PUSH, XED_REG_X87STATUS, XED_REG_X87TAG, XED_REG_XCR0, XED_REG_XMM0, XED_REG_XMM1, XED_REG_XMM10, XED_REG_XMM11, XED_REG_XMM12, XED_REG_XMM13, XED_REG_XMM14, XED_REG_XMM15, XED_REG_XMM16, XED_REG_XMM17, XED_REG_XMM18, XED_REG_XMM19, XED_REG_XMM2, XED_REG_XMM20, XED_REG_XMM21, XED_REG_XMM22, XED_REG_XMM23, XED_REG_XMM24, XED_REG_XMM25, XED_REG_XMM26, XED_REG_XMM27, XED_REG_XMM28, XED_REG_XMM29, XED_REG_XMM3, XED_REG_XMM30, XED_REG_XMM31, XED_REG_XMM4, XED_REG_XMM5, XED_REG_XMM6, XED_REG_XMM7, XED_REG_XMM8, XED_REG_XMM9, XED_REG_YMM0, XED_REG_YMM1, XED_REG_YMM10, XED_REG_YMM11, XED_REG_YMM12, XED_REG_YMM13, XED_REG_YMM14, XED_REG_YMM15, XED_REG_YMM16, XED_REG_YMM17, XED_REG_YMM18, XED_REG_YMM19, XED_REG_YMM2, XED_REG_YMM20, XED_REG_YMM21, XED_REG_YMM22, XED_REG_YMM23, XED_REG_YMM24, XED_REG_YMM25, XED_REG_YMM26, XED_REG_YMM27, XED_REG_YMM28, XED_REG_YMM29, XED_REG_YMM3, XED_REG_YMM30, XED_REG_YMM31, XED_REG_YMM4, XED_REG_YMM5, XED_REG_YMM6, XED_REG_YMM7, XED_REG_YMM8, XED_REG_YMM9, XED_REG_ZMM0, XED_REG_ZMM1, XED_REG_ZMM10, XED_REG_ZMM11, XED_REG_ZMM12, XED_REG_ZMM13, XED_REG_ZMM14, XED_REG_ZMM15, XED_REG_ZMM16, XED_REG_ZMM17, XED_REG_ZMM18, XED_REG_ZMM19, XED_REG_ZMM2, XED_REG_ZMM20, XED_REG_ZMM21, XED_REG_ZMM22, XED_REG_ZMM23, XED_REG_ZMM24, XED_REG_ZMM25, XED_REG_ZMM26, XED_REG_ZMM27, XED_REG_ZMM28, XED_REG_ZMM29, XED_REG_ZMM3, XED_REG_ZMM30, XED_REG_ZMM31, XED_REG_ZMM4, XED_REG_ZMM5, XED_REG_ZMM6, XED_REG_ZMM7, XED_REG_ZMM8, XED_REG_ZMM9};

#[allow(non_camel_case_types)]
pub enum OperandReg {
    BNDCFGU,
    BNDSTATUS,
    BND0,
    BND1,
    BND2,
    BND3,
    CR0,
    CR1,
    CR2,
    CR3,
    CR4,
    CR5,
    CR6,
    CR7,
    CR8,
    CR9,
    CR10,
    CR11,
    CR12,
    CR13,
    CR14,
    CR15,
    DR0,
    DR1,
    DR2,
    DR3,
    DR4,
    DR5,
    DR6,
    DR7,
    FLAGS,
    EFLAGS,
    RFLAGS,
    AX,
    CX,
    DX,
    BX,
    SP,
    BP,
    SI,
    DI,
    R8W,
    R9W,
    R10W,
    R11W,
    R12W,
    R13W,
    R14W,
    R15W,
    EAX,
    ECX,
    EDX,
    EBX,
    ESP,
    EBP,
    ESI,
    EDI,
    R8D,
    R9D,
    R10D,
    R11D,
    R12D,
    R13D,
    R14D,
    R15D,
    RAX,
    RCX,
    RDX,
    RBX,
    RSP,
    RBP,
    RSI,
    RDI,
    R8,
    R9,
    R10,
    R11,
    R12,
    R13,
    R14,
    R15,
    AL,
    CL,
    DL,
    BL,
    SPL,
    BPL,
    SIL,
    DIL,
    R8B,
    R9B,
    R10B,
    R11B,
    R12B,
    R13B,
    R14B,
    R15B,
    AH,
    CH,
    DH,
    BH,
    ERROR,
    RIP,
    EIP,
    IP,
    K0,
    K1,
    K2,
    K3,
    K4,
    K5,
    K6,
    K7,
    MMX0,
    MMX1,
    MMX2,
    MMX3,
    MMX4,
    MMX5,
    MMX6,
    MMX7,
    SSP,
    IA32_U_CET,
    MXCSR,
    STACKPUSH,
    STACKPOP,
    GDTR,
    LDTR,
    IDTR,
    TR,
    TSC,
    TSCAUX,
    MSRS,
    FSBASE,
    GSBASE,
    TILECONFIG,
    X87CONTROL,
    X87STATUS,
    X87TAG,
    X87PUSH,
    X87POP,
    X87POP2,
    X87OPCODE,
    X87LASTCS,
    X87LASTIP,
    X87LASTDS,
    X87LASTDP,
    ES,
    CS,
    SS,
    DS,
    FS,
    GS,
    TMP0,
    TMP1,
    TMP2,
    TMP3,
    TMP4,
    TMP5,
    TMP6,
    TMP7,
    TMP8,
    TMP9,
    TMP10,
    TMP11,
    TMP12,
    TMP13,
    TMP14,
    TMP15,
    TMM0,
    TMM1,
    TMM2,
    TMM3,
    TMM4,
    TMM5,
    TMM6,
    TMM7,
    UIF,
    ST0,
    ST1,
    ST2,
    ST3,
    ST4,
    ST5,
    ST6,
    ST7,
    XCR0,
    XMM0,
    XMM1,
    XMM2,
    XMM3,
    XMM4,
    XMM5,
    XMM6,
    XMM7,
    XMM8,
    XMM9,
    XMM10,
    XMM11,
    XMM12,
    XMM13,
    XMM14,
    XMM15,
    XMM16,
    XMM17,
    XMM18,
    XMM19,
    XMM20,
    XMM21,
    XMM22,
    XMM23,
    XMM24,
    XMM25,
    XMM26,
    XMM27,
    XMM28,
    XMM29,
    XMM30,
    XMM31,
    YMM0,
    YMM1,
    YMM2,
    YMM3,
    YMM4,
    YMM5,
    YMM6,
    YMM7,
    YMM8,
    YMM9,
    YMM10,
    YMM11,
    YMM12,
    YMM13,
    YMM14,
    YMM15,
    YMM16,
    YMM17,
    YMM18,
    YMM19,
    YMM20,
    YMM21,
    YMM22,
    YMM23,
    YMM24,
    YMM25,
    YMM26,
    YMM27,
    YMM28,
    YMM29,
    YMM30,
    YMM31,
    ZMM0,
    ZMM1,
    ZMM2,
    ZMM3,
    ZMM4,
    ZMM5,
    ZMM6,
    ZMM7,
    ZMM8,
    ZMM9,
    ZMM10,
    ZMM11,
    ZMM12,
    ZMM13,
    ZMM14,
    ZMM15,
    ZMM16,
    ZMM17,
    ZMM18,
    ZMM19,
    ZMM20,
    ZMM21,
    ZMM22,
    ZMM23,
    ZMM24,
    ZMM25,
    ZMM26,
    ZMM27,
    ZMM28,
    ZMM29,
    ZMM30,
    ZMM31,
    LAST,
    BNDCFG_FIRST,
    BNDCFG_LAST,
    BNDSTAT_FIRST,
    BNDSTAT_LAST,
    BOUND_FIRST,
    BOUND_LAST,
    CR_FIRST,
    CR_LAST,
    DR_FIRST,
    DR_LAST,
    FLAGS_FIRST,
    FLAGS_LAST,
    GPR16_FIRST,
    GPR16_LAST,
    GPR32_FIRST,
    GPR32_LAST,
    GPR64_FIRST,
    GPR64_LAST,
    GPR8_FIRST,
    GPR8_LAST,
    GPR8h_FIRST,
    GPR8h_LAST,
    INVALID_FIRST,
    INVALID_LAST,
    IP_FIRST,
    IP_LAST,
    MASK_FIRST,
    MASK_LAST,
    MMX_FIRST,
    MMX_LAST,
    MSR_FIRST,
    MSR_LAST,
    MXCSR_FIRST,
    MXCSR_LAST,
    PSEUDO_FIRST,
    PSEUDO_LAST,
    PSEUDOX87_FIRST,
    PSEUDOX87_LAST,
    SR_FIRST,
    SR_LAST,
    TMP_FIRST,
    TMP_LAST,
    TREG_FIRST,
    TREG_LAST,
    UIF_FIRST,
    UIF_LAST,
    X87_FIRST,
    X87_LAST,
    XCR_FIRST,
    XCR_LAST,
    XMM_FIRST,
    XMM_LAST,
    YMM_FIRST,
    YMM_LAST,
    ZMM_FIRST,
}

impl OperandReg {
    pub fn new(xed: xed_reg_class_enum_t) -> Self {
        match xed {
            XED_REG_BNDCFGU => Self::BNDCFGU,
            XED_REG_BNDSTATUS => Self::BNDSTATUS,
            XED_REG_BND0 => Self::BND0,
            XED_REG_BND1 => Self::BND1,
            XED_REG_BND2 => Self::BND2,
            XED_REG_BND3 => Self::BND3,
            XED_REG_CR0 => Self::CR0,
            XED_REG_CR1 => Self::CR1,
            XED_REG_CR2 => Self::CR2,
            XED_REG_CR3 => Self::CR3,
            XED_REG_CR4 => Self::CR4,
            XED_REG_CR5 => Self::CR5,
            XED_REG_CR6 => Self::CR6,
            XED_REG_CR7 => Self::CR7,
            XED_REG_CR8 => Self::CR8,
            XED_REG_CR9 => Self::CR9,
            XED_REG_CR10 => Self::CR10,
            XED_REG_CR11 => Self::CR11,
            XED_REG_CR12 => Self::CR12,
            XED_REG_CR13 => Self::CR13,
            XED_REG_CR14 => Self::CR14,
            XED_REG_CR15 => Self::CR15,
            XED_REG_DR0 => Self::DR0,
            XED_REG_DR1 => Self::DR1,
            XED_REG_DR2 => Self::DR2,
            XED_REG_DR3 => Self::DR3,
            XED_REG_DR4 => Self::DR4,
            XED_REG_DR5 => Self::DR5,
            XED_REG_DR6 => Self::DR6,
            XED_REG_DR7 => Self::DR7,
            XED_REG_FLAGS => Self::FLAGS,
            XED_REG_EFLAGS => Self::EFLAGS,
            XED_REG_RFLAGS => Self::RFLAGS,
            XED_REG_AX => Self::AX,
            XED_REG_CX => Self::CX,
            XED_REG_DX => Self::DX,
            XED_REG_BX => Self::BX,
            XED_REG_SP => Self::SP,
            XED_REG_BP => Self::BP,
            XED_REG_SI => Self::SI,
            XED_REG_DI => Self::DI,
            XED_REG_R8W => Self::R8W,
            XED_REG_R9W => Self::R9W,
            XED_REG_R10W => Self::R10W,
            XED_REG_R11W => Self::R11W,
            XED_REG_R12W => Self::R12W,
            XED_REG_R13W => Self::R13W,
            XED_REG_R14W => Self::R14W,
            XED_REG_R15W => Self::R15W,
            XED_REG_EAX => Self::EAX,
            XED_REG_ECX => Self::ECX,
            XED_REG_EDX => Self::EDX,
            XED_REG_EBX => Self::EBX,
            XED_REG_ESP => Self::ESP,
            XED_REG_EBP => Self::EBP,
            XED_REG_ESI => Self::ESI,
            XED_REG_EDI => Self::EDI,
            XED_REG_R8D => Self::R8D,
            XED_REG_R9D => Self::R9D,
            XED_REG_R10D => Self::R10D,
            XED_REG_R11D => Self::R11D,
            XED_REG_R12D => Self::R12D,
            XED_REG_R13D => Self::R13D,
            XED_REG_R14D => Self::R14D,
            XED_REG_R15D => Self::R15D,
            XED_REG_RAX => Self::RAX,
            XED_REG_RCX => Self::RCX,
            XED_REG_RDX => Self::RDX,
            XED_REG_RBX => Self::RBX,
            XED_REG_RSP => Self::RSP,
            XED_REG_RBP => Self::RBP,
            XED_REG_RSI => Self::RSI,
            XED_REG_RDI => Self::RDI,
            XED_REG_R8 => Self::R8,
            XED_REG_R9 => Self::R9,
            XED_REG_R10 => Self::R10,
            XED_REG_R11 => Self::R11,
            XED_REG_R12 => Self::R12,
            XED_REG_R13 => Self::R13,
            XED_REG_R14 => Self::R14,
            XED_REG_R15 => Self::R15,
            XED_REG_AL => Self::AL,
            XED_REG_CL => Self::CL,
            XED_REG_DL => Self::DL,
            XED_REG_BL => Self::BL,
            XED_REG_SPL => Self::SPL,
            XED_REG_BPL => Self::BPL,
            XED_REG_SIL => Self::SIL,
            XED_REG_DIL => Self::DIL,
            XED_REG_R8B => Self::R8B,
            XED_REG_R9B => Self::R9B,
            XED_REG_R10B => Self::R10B,
            XED_REG_R11B => Self::R11B,
            XED_REG_R12B => Self::R12B,
            XED_REG_R13B => Self::R13B,
            XED_REG_R14B => Self::R14B,
            XED_REG_R15B => Self::R15B,
            XED_REG_AH => Self::AH,
            XED_REG_CH => Self::CH,
            XED_REG_DH => Self::DH,
            XED_REG_BH => Self::BH,
            XED_REG_ERROR => Self::ERROR,
            XED_REG_RIP => Self::RIP,
            XED_REG_EIP => Self::EIP,
            XED_REG_IP => Self::IP,
            XED_REG_K0 => Self::K0,
            XED_REG_K1 => Self::K1,
            XED_REG_K2 => Self::K2,
            XED_REG_K3 => Self::K3,
            XED_REG_K4 => Self::K4,
            XED_REG_K5 => Self::K5,
            XED_REG_K6 => Self::K6,
            XED_REG_K7 => Self::K7,
            XED_REG_MMX0 => Self::MMX0,
            XED_REG_MMX1 => Self::MMX1,
            XED_REG_MMX2 => Self::MMX2,
            XED_REG_MMX3 => Self::MMX3,
            XED_REG_MMX4 => Self::MMX4,
            XED_REG_MMX5 => Self::MMX5,
            XED_REG_MMX6 => Self::MMX6,
            XED_REG_MMX7 => Self::MMX7,
            XED_REG_SSP => Self::SSP,
            XED_REG_IA32_U_CET => Self::IA32_U_CET,
            XED_REG_MXCSR => Self::MXCSR,
            XED_REG_STACKPUSH => Self::STACKPUSH,
            XED_REG_STACKPOP => Self::STACKPOP,
            XED_REG_GDTR => Self::GDTR,
            XED_REG_LDTR => Self::LDTR,
            XED_REG_IDTR => Self::IDTR,
            XED_REG_TR => Self::TR,
            XED_REG_TSC => Self::TSC,
            XED_REG_TSCAUX => Self::TSCAUX,
            XED_REG_MSRS => Self::MSRS,
            XED_REG_FSBASE => Self::FSBASE,
            XED_REG_GSBASE => Self::GSBASE,
            XED_REG_TILECONFIG => Self::TILECONFIG,
            XED_REG_X87CONTROL => Self::X87CONTROL,
            XED_REG_X87STATUS => Self::X87STATUS,
            XED_REG_X87TAG => Self::X87TAG,
            XED_REG_X87PUSH => Self::X87PUSH,
            XED_REG_X87POP => Self::X87POP,
            XED_REG_X87POP2 => Self::X87POP2,
            XED_REG_X87OPCODE => Self::X87OPCODE,
            XED_REG_X87LASTCS => Self::X87LASTCS,
            XED_REG_X87LASTIP => Self::X87LASTIP,
            XED_REG_X87LASTDS => Self::X87LASTDS,
            XED_REG_X87LASTDP => Self::X87LASTDP,
            XED_REG_ES => Self::ES,
            XED_REG_CS => Self::CS,
            XED_REG_SS => Self::SS,
            XED_REG_DS => Self::DS,
            XED_REG_FS => Self::FS,
            XED_REG_GS => Self::GS,
            XED_REG_TMP0 => Self::TMP0,
            XED_REG_TMP1 => Self::TMP1,
            XED_REG_TMP2 => Self::TMP2,
            XED_REG_TMP3 => Self::TMP3,
            XED_REG_TMP4 => Self::TMP4,
            XED_REG_TMP5 => Self::TMP5,
            XED_REG_TMP6 => Self::TMP6,
            XED_REG_TMP7 => Self::TMP7,
            XED_REG_TMP8 => Self::TMP8,
            XED_REG_TMP9 => Self::TMP9,
            XED_REG_TMP10 => Self::TMP10,
            XED_REG_TMP11 => Self::TMP11,
            XED_REG_TMP12 => Self::TMP12,
            XED_REG_TMP13 => Self::TMP13,
            XED_REG_TMP14 => Self::TMP14,
            XED_REG_TMP15 => Self::TMP15,
            XED_REG_TMM0 => Self::TMM0,
            XED_REG_TMM1 => Self::TMM1,
            XED_REG_TMM2 => Self::TMM2,
            XED_REG_TMM3 => Self::TMM3,
            XED_REG_TMM4 => Self::TMM4,
            XED_REG_TMM5 => Self::TMM5,
            XED_REG_TMM6 => Self::TMM6,
            XED_REG_TMM7 => Self::TMM7,
            XED_REG_UIF => Self::UIF,
            XED_REG_ST0 => Self::ST0,
            XED_REG_ST1 => Self::ST1,
            XED_REG_ST2 => Self::ST2,
            XED_REG_ST3 => Self::ST3,
            XED_REG_ST4 => Self::ST4,
            XED_REG_ST5 => Self::ST5,
            XED_REG_ST6 => Self::ST6,
            XED_REG_ST7 => Self::ST7,
            XED_REG_XCR0 => Self::XCR0,
            XED_REG_XMM0 => Self::XMM0,
            XED_REG_XMM1 => Self::XMM1,
            XED_REG_XMM2 => Self::XMM2,
            XED_REG_XMM3 => Self::XMM3,
            XED_REG_XMM4 => Self::XMM4,
            XED_REG_XMM5 => Self::XMM5,
            XED_REG_XMM6 => Self::XMM6,
            XED_REG_XMM7 => Self::XMM7,
            XED_REG_XMM8 => Self::XMM8,
            XED_REG_XMM9 => Self::XMM9,
            XED_REG_XMM10 => Self::XMM10,
            XED_REG_XMM11 => Self::XMM11,
            XED_REG_XMM12 => Self::XMM12,
            XED_REG_XMM13 => Self::XMM13,
            XED_REG_XMM14 => Self::XMM14,
            XED_REG_XMM15 => Self::XMM15,
            XED_REG_XMM16 => Self::XMM16,
            XED_REG_XMM17 => Self::XMM17,
            XED_REG_XMM18 => Self::XMM18,
            XED_REG_XMM19 => Self::XMM19,
            XED_REG_XMM20 => Self::XMM20,
            XED_REG_XMM21 => Self::XMM21,
            XED_REG_XMM22 => Self::XMM22,
            XED_REG_XMM23 => Self::XMM23,
            XED_REG_XMM24 => Self::XMM24,
            XED_REG_XMM25 => Self::XMM25,
            XED_REG_XMM26 => Self::XMM26,
            XED_REG_XMM27 => Self::XMM27,
            XED_REG_XMM28 => Self::XMM28,
            XED_REG_XMM29 => Self::XMM29,
            XED_REG_XMM30 => Self::XMM30,
            XED_REG_XMM31 => Self::XMM31,
            XED_REG_YMM0 => Self::YMM0,
            XED_REG_YMM1 => Self::YMM1,
            XED_REG_YMM2 => Self::YMM2,
            XED_REG_YMM3 => Self::YMM3,
            XED_REG_YMM4 => Self::YMM4,
            XED_REG_YMM5 => Self::YMM5,
            XED_REG_YMM6 => Self::YMM6,
            XED_REG_YMM7 => Self::YMM7,
            XED_REG_YMM8 => Self::YMM8,
            XED_REG_YMM9 => Self::YMM9,
            XED_REG_YMM10 => Self::YMM10,
            XED_REG_YMM11 => Self::YMM11,
            XED_REG_YMM12 => Self::YMM12,
            XED_REG_YMM13 => Self::YMM13,
            XED_REG_YMM14 => Self::YMM14,
            XED_REG_YMM15 => Self::YMM15,
            XED_REG_YMM16 => Self::YMM16,
            XED_REG_YMM17 => Self::YMM17,
            XED_REG_YMM18 => Self::YMM18,
            XED_REG_YMM19 => Self::YMM19,
            XED_REG_YMM20 => Self::YMM20,
            XED_REG_YMM21 => Self::YMM21,
            XED_REG_YMM22 => Self::YMM22,
            XED_REG_YMM23 => Self::YMM23,
            XED_REG_YMM24 => Self::YMM24,
            XED_REG_YMM25 => Self::YMM25,
            XED_REG_YMM26 => Self::YMM26,
            XED_REG_YMM27 => Self::YMM27,
            XED_REG_YMM28 => Self::YMM28,
            XED_REG_YMM29 => Self::YMM29,
            XED_REG_YMM30 => Self::YMM30,
            XED_REG_YMM31 => Self::YMM31,
            XED_REG_ZMM0 => Self::ZMM0,
            XED_REG_ZMM1 => Self::ZMM1,
            XED_REG_ZMM2 => Self::ZMM2,
            XED_REG_ZMM3 => Self::ZMM3,
            XED_REG_ZMM4 => Self::ZMM4,
            XED_REG_ZMM5 => Self::ZMM5,
            XED_REG_ZMM6 => Self::ZMM6,
            XED_REG_ZMM7 => Self::ZMM7,
            XED_REG_ZMM8 => Self::ZMM8,
            XED_REG_ZMM9 => Self::ZMM9,
            XED_REG_ZMM10 => Self::ZMM10,
            XED_REG_ZMM11 => Self::ZMM11,
            XED_REG_ZMM12 => Self::ZMM12,
            XED_REG_ZMM13 => Self::ZMM13,
            XED_REG_ZMM14 => Self::ZMM14,
            XED_REG_ZMM15 => Self::ZMM15,
            XED_REG_ZMM16 => Self::ZMM16,
            XED_REG_ZMM17 => Self::ZMM17,
            XED_REG_ZMM18 => Self::ZMM18,
            XED_REG_ZMM19 => Self::ZMM19,
            XED_REG_ZMM20 => Self::ZMM20,
            XED_REG_ZMM21 => Self::ZMM21,
            XED_REG_ZMM22 => Self::ZMM22,
            XED_REG_ZMM23 => Self::ZMM23,
            XED_REG_ZMM24 => Self::ZMM24,
            XED_REG_ZMM25 => Self::ZMM25,
            XED_REG_ZMM26 => Self::ZMM26,
            XED_REG_ZMM27 => Self::ZMM27,
            XED_REG_ZMM28 => Self::ZMM28,
            XED_REG_ZMM29 => Self::ZMM29,
            XED_REG_ZMM30 => Self::ZMM30,
            XED_REG_ZMM31 => Self::ZMM31,
            XED_REG_LAST => Self::LAST,
            XED_REG_INVALID_FIRST => Self::INVALID_FIRST,
            _ => panic!()
        }
    }
}